var list=[

"😀face | grin",
"😁eye | face | grin | smile",
"😂face | joy | laugh| tear",
"😃face | mouth | smile",
"😄eye | face | mouth | smile",
"😅cold | face |smile | sweat",
"😆face | laugh | mouth | satisfied | smile",
"😉face | wink",
"😊blush | eye | face| smile",
"😋delicious | face | savouring | smile| um | yum",
"😎bright | cool | eye| eyewear | face | glasses | smile | sun | sunglasses",
"😍eye | face | love | smile",
"😘face | kiss",
"😗face | kiss",
"😙eye | face | kiss | smile",
"😚closed | eye | face | kiss",
"☺face | outlined | relaxed | smile",
"🙂face | smile",
"🤗face | hug | hugging",
"🤔face | thinking",
"😐deadpan | face | neutral",
"😑expressionless | face | inexpressive | unexpressive",
"😶face | mouth | quiet | silent",
"🙄eyes | face | rolling",
"😏face | smirk",
"😣face | persevere",
"😥disappointed | face | relieved | whew",
"😮face | mouth | sympathy",
"🤐face | mouth | zipper",
"😯face | hushed | stunned | surprised",
"😪face | sleep",
"😫face | tired",
"😴face | sleep | zzz",
"😌face | relieved",
"🤓face | geek | nerd",
"😛face | tongue",
"😜eye | face | joke | tongue | wink",
"😝eye | face | horrible | taste | tongue",
"🤤drooling | face",
"😒face | unamused| unhappy",
"😓cold | face | sweat",
"😔dejected | face | pensive",
"😕confused | face",
"🙃face | upside-down",
"🤑face | money | mouth",
"😲astonished | face| shocked | totally",
"☹face | frown",
"🙁face | frown",
"😖confounded | face",
"😞disappointed | face",
"😟face | worried",
"😤face | triumph | won",
"😢cry | face | sad | tear",
"😭cry | face | sad | sob | tear",
"😦face | frown | mouth",
"😧anguished | face",
"😨face | fear | fearful | scared",
"😩face | tired | weary",
"😬face | grimace",
"😰blue | cold | face| mouth | rushed | sweat",
"😱face | fear | fearful | munch | scared | scream",
"😳dazed | face | flushed",
"😵dizzy | face",
"😡angry | face | mad | pouting | rage | red",
"😠angry | face | mad",
"😇angel | face | fairytale | fantasy | halo | innocent | smile",
"🤠cowboy | cowgirl| face | hat",
"🤡clown | face",
"🤥face | lie | pinocchio",
"😷cold | doctor | face | mask | medicine | sick",
"🤒face | ill | sick | thermometer",
"🤕bandage | face | hurt | injury",
"🤢face | nauseated| vomit",
"🤧face | gesundheit| sneeze",
"😈face | fairytale | fantasy | horns | smile",
"👿demon | devil | face | fairytale | fantasy | imp",
"👹creature | face | fairytale | fantasy | Japanese | monster",
"👺creature | face | fairytale | fantasy | Japanese | monster",
"💀death | face | fairytale | monster",
"☠crossbones | death | face | monster | skull",
"👻creature | face | fairytale | fantasy | monster",
"👽creature | extraterrestrial | face | fairytale | fantasy | monster | ufo",
"👾alien | creature | extraterrestrial | face | fairytale | fantasy | monster | ufo",
"🤖face | monster | robot",
"💩comic | dung | face | monster | poo | poop",
"😺cat | face | mouth | smile",
"😸cat | eye | face | grin | smile",
"😹cat | face | joy | tear",
"😻cat | eye | face | love | smile",
"😼cat | face | ironic| smile | wry",
"😽cat | eye | face | kiss",
"🙀cat | face | oh | surprised | weary",
"😿cat | cry | face | sad | tear",
"😾cat | face | pouting",
"🙈evil | face | forbidden | gesture | monkey | no | not | prohibited | see",
"🙉evil | face | forbidden | gesture | hear | monkey | no | not | prohibited",
"🙊evil | face | forbidden | gesture | monkey | no | not | prohibited | speak",
"👦boy | young",
"👦🏻boy | lightskintone | young",
"👦🏼boy | medium-lightskintone | young",
"👦🏽boy | mediumskintone | young",
"👦🏾boy | medium-darkskintone | young",
"👦🏿boy | darkskintone | young",
"👧Virgo | young | zodiac",
"👧🏻lightskintone | Virgo | young | zodiac",
"👧🏼medium-lightskintone | Virgo| young | zodiac",
"👧🏽mediumskintone | Virgo | young | zodiac",
"👧🏾medium-darkskintone | Virgo| young | zodiac",
"👧🏿darkskintone | Virgo | young | zodiac",
"👨man",
"👨🏻lightskintone | man",
"👨🏼man | medium-lightskintone",
"👨🏽man | mediumskintone",
"👨🏾man | medium-darkskintone",
"👨🏿darkskintone | man",
"👩woman",
"👩🏻lightskintone | woman",
"👩🏼medium-lightskintone | woman",
"👩🏽mediumskintone | woman",
"👩🏾medium-darkskintone | woman",
"👩🏿darkskintone | woman",
"👴man | old",
"👴🏻lightskintone | man | old",
"👴🏼man | medium-lightskintone | old",
"👴🏽man | mediumskintone | old",
"👴🏾man | medium-darkskintone | old",
"👴🏿darkskintone | man | old",
"👵old | woman",
"👵🏻lightskintone | old | woman",
"👵🏼medium-lightskintone | old | woman",
"👵🏽mediumskintone | old | woman",
"👵🏾medium-darkskintone | old | woman",
"👵🏿darkskintone | old | woman",
"👶baby | young",
"👶🏻baby | lightskintone | young",
"👶🏼baby | medium-lightskintone | young",
"👶🏽baby | mediumskintone | young",
"👶🏾baby | medium-darkskintone | young",
"👶🏿baby | darkskintone | young",
"👼angel | baby | face | fairytale | fantasy",
"👼🏻angel | baby | face | fairytale | fantasy | lightskintone",
"👼🏼angel | baby | face | fairytale | fantasy | medium-lightskintone",
"👼🏽angel | baby | face | fairytale | fantasy | mediumskintone",
"👼🏾angel | baby | face | fairytale | fantasy | medium-darkskintone",
"👼🏿angel | baby | darkskintone | face | fairytale | fantasy",
"👮cop | officer | police",
"👮🏻cop | lightskintone | officer | police",
"👮🏼cop | medium-lightskintone | officer | police",
"👮🏽cop | mediumskintone | officer| police",
"👮🏾cop | medium-darkskintone | officer | police",
"👮🏿cop | darkskintone | officer | police",
"🕵detective | sleuth| spy",
"🕵🏻detective | lightskintone | sleuth| spy",
"🕵🏼detective | medium-lightskintone | sleuth| spy",
"🕵🏽detective | mediumskintone | sleuth | spy",
"🕵🏾detective | medium-darkskintone | sleuth| spy",
"🕵🏿darkskintone | detective | sleuth| spy",
"💂guard",
"💂🏻guard | lightskintone",
"💂🏼guard | medium-lightskintone",
"💂🏽guard | mediumskintone",
"💂🏾guard | medium-darkskintone",
"💂🏿darkskintone | guard",
"👷construction | hat| worker",
"👷🏻construction | hat| lightskintone | worker",
"👷🏼construction | hat| medium-lightskintone | worker",
"👷🏽construction | hat| mediumskintone | worker",
"👷🏾construction | hat| medium-darkskintone | worker",
"👷🏿construction | darkskintone | hat | worker",
"👳turban",
"👳🏻lightskintone | turban",
"👳🏼medium-lightskintone | turban",
"👳🏽mediumskintone | turban",
"👳🏾medium-darkskintone | turban",
"👳🏿darkskintone | turban",
"👱blond",
"👱🏻blond | lightskintone",
"👱🏼blond | medium-lightskintone",
"👱🏽blond | mediumskintone",
"👱🏾blond | medium-darkskintone",
"👱🏿blond | darkskintone",
"🎅celebration | Christmas | claus | father | santa",
"👸fairytale | fantasy",
"👸🏻fairytale | fantasy | lightskintone",
"👸🏼fairytale | fantasy | medium-lightskintone",
"👸🏽fairytale | fantasy | mediumskintone",
"👸🏾fairytale | fantasy | medium-darkskintone",
"👸🏿darkskintone | fairytale | fantasy",
"👰bride | veil | wedding",
"👰🏻bride | lightskintone | veil | wedding",
"👰🏼bride | medium-lightskintone | veil | wedding",
"👰🏽bride | mediumskintone | veil | wedding",
"👰🏾bride | medium-darkskintone | veil | wedding",
"👰🏿bride | darkskintone | veil | wedding",
"🤵groom | man | tuxedo",
"🤵🏻groom | lightskintone | man | tuxedo",
"🤵🏼groom | man | medium-lightskintone | tuxedo",
"🤵🏽groom | man | mediumskintone | tuxedo",
"🤵🏾groom | man | medium-darkskintone | tuxedo",
"🤵🏿darkskintone | groom | man | tuxedo",
"🤰pregnant | woman",
"🤰🏻lightskintone | pregnant | woman",
"🤰🏼medium-lightskintone | pregnant | woman",
"🤰🏽mediumskintone | pregnant | woman",
"🤰🏾medium-darkskintone | pregnant | woman",
"🤰🏿darkskintone | pregnant | woman",
"👲guapimao | hat| man",
"👲🏻guapimao | hat| lightskintone | man",
"👲🏼guapimao | hat| man | medium-lightskintone",
"👲🏽guapimao | hat| man | mediumskintone",
"👲🏾guapimao | hat| man | medium-darkskintone",
"👲🏿darkskintone | guapimao | hat| man",
"🙍frown | gesture",
"🙍🏻frown | gesture | lightskintone",
"🙍🏼frown | gesture | medium-lightskintone",
"🙍🏽frown | gesture | mediumskintone",
"🙍🏾frown | gesture | medium-darkskintone",
"🙍🏿darkskintone | frown | gesture",
"🙎gesture | pouting",
"🙎🏻gesture | lightskintone | pouting",
"🙎🏼gesture | medium-lightskintone | pouting",
"🙎🏽gesture | mediumskintone | pouting",
"🙎🏾gesture | medium-darkskintone | pouting",
"🙎🏿darkskintone | gesture | pouting",
"🙅forbidden | gesture | hand | no | not | prohibited",
"🙅🏻forbidden | gesture | hand | lightskintone | no | not | prohibited",
"🙅🏼forbidden | gesture | hand | medium-lightskintone | no | not | prohibited",
"🙅🏽forbidden | gesture | hand | mediumskintone | no | not | prohibited",
"🙅🏾forbidden | gesture | hand | medium-darkskintone | no | not | prohibited",
"🙅🏿darkskintone | forbidden | gesture | hand | no | not | prohibited",
"🙆gesture | hand | OK",
"🙆🏻gesture | hand | lightskintone | OK",
"🙆🏼gesture | hand | medium-lightskintone | OK",
"🙆🏽gesture | hand | mediumskintone | OK",
"🙆🏾gesture | hand | medium-darkskintone | OK",
"🙆🏿darkskintone | gesture | hand | OK",
"💁hand | help | information | sassy | tipping",
"💁🏻hand | help | information | lightskintone | sassy| tipping",
"💁🏼hand | help | information | medium-lightskintone | sassy| tipping",
"💁🏽hand | help | information | mediumskintone | sassy | tipping",
"💁🏾hand | help | information | medium-darkskintone | sassy| tipping",
"💁🏿darkskintone | hand | help | information | sassy | tipping",
"🙋gesture | hand | happy | raised",
"🙋🏻gesture | hand | happy | lightskintone | raised",
"🙋🏼gesture | hand | happy | medium-lightskintone | raised",
"🙋🏽gesture | hand | happy | mediumskintone | raised",
"🙋🏾gesture | hand | happy | medium-darkskintone | raised",
"🙋🏿darkskintone | gesture | hand | happy | raised",
"🙇apology | bow | gesture | sorry",
"🙇🏻apology | bow | gesture | lightskintone | sorry",
"🙇🏼apology | bow | gesture | medium-lightskintone | sorry",
"🙇🏽apology | bow | gesture | mediumskintone | sorry",
"🙇🏾apology | bow | gesture | medium-darkskintone | sorry",
"🙇🏿apology | bow | darkskintone | gesture | sorry",
"💆face | massage | salon",
"💆🏻face | lightskintone | massage | salon",
"💆🏼face | massage | medium-lightskintone | salon",
"💆🏽face | massage | mediumskintone | salon",
"💆🏾face | massage | medium-darkskintone | salon",
"💆🏿darkskintone | face | massage | salon",
"💇barber | beauty | haircut | parlor",
"💇🏻barber | beauty | haircut | lightskintone | parlor",
"💇🏼barber | beauty | haircut | medium-lightskintone | parlor",
"💇🏽barber | beauty | haircut | mediumskintone | parlor",
"💇🏾barber | beauty | haircut | medium-darkskintone | parlor",
"💇🏿barber | beauty | darkskintone | haircut | parlor",
"🚶hike | walk | walking",
"🚶🏻hike | lightskintone | walk | walking",
"🚶🏼hike | medium-lightskintone | walk | walking",
"🚶🏽hike | mediumskintone | walk | walking",
"🚶🏾hike | medium-darkskintone | walk | walking",
"🚶🏿darkskintone | hike | walk | walking",
"🏃marathon | running",
"🏃🏻lightskintone | marathon | running",
"🏃🏼marathon | medium-lightskintone | running",
"🏃🏽marathon | mediumskintone | running",
"🏃🏾marathon | medium-darkskintone | running",
"🏃🏿darkskintone | marathon | running",
"💃dancing | woman",
"💃🏻dancing | lightskintone | woman",
"💃🏼dancing | medium-lightskintone | woman",
"💃🏽dancing | mediumskintone | woman",
"💃🏾dancing | medium-darkskintone | woman",
"💃🏿dancing | darkskintone | woman",
"🕺dance | man",
"🕺🏻dance | lightskintone | man",
"🕺🏼dance | man | medium-lightskintone",
"🕺🏽dance | man | mediumskintone",
"🕺🏾dance | man | medium-darkskintone",
"🕺🏿dance | darkskintone | man",
"👯bunnyear | dancer | partying",
"🕴business | man | suit",
"🗣face | head | silhouette | speak | speaking",
"👤bust | silhouette",
"👥bust | silhouette",
"🤺fencer | fencing | sword",
"🏇horse | jockey | racehorse | racing",
"🏇🏻horse | jockey | lightskintone | racehorse | racing",
"🏇🏼horse | jockey | medium-lightskintone | racehorse | racing",
"🏇🏽horse | jockey | mediumskintone | racehorse| racing",
"🏇🏾horse | jockey | medium-darkskintone | racehorse | racing",
"🏇🏿darkskintone | horse | jockey | racehorse | racing",
"⛷ski | snow",
"🏂ski | snow | snowboard",
"🏌ball | golf",
"🏄surfing",
"🏄🏻lightskintone | surfing",
"🏄🏼medium-lightskintone | surfing",
"🏄🏽mediumskintone | surfing",
"🏄🏾medium-darkskintone | surfing",
"🏄🏿darkskintone | surfing",
"🚣boat | rowboat",
"🚣🏻boat | lightskintone | rowboat",
"🚣🏼boat | medium-lightskintone | rowboat",
"🚣🏽boat | mediumskintone | rowboat",
"🚣🏾boat | medium-darkskintone | rowboat",
"🚣🏿boat | darkskintone | rowboat",
"🏊swim",
"🏊🏻lightskintone | swim",
"🏊🏼medium-lightskintone | swim",
"🏊🏽mediumskintone | swim",
"🏊🏾medium-darkskintone | swim",
"🏊🏿darkskintone | swim",
"⛹ball",
"⛹🏻ball | lightskintone",
"⛹🏼ball | medium-lightskintone",
"⛹🏽ball | mediumskintone",
"⛹🏾ball | medium-darkskintone",
"⛹🏿ball | darkskintone",
"🏋lifter | weight",
"🏋🏻lifter | lightskintone | weight",
"🏋🏼lifter | medium-lightskintone | weight",
"🏋🏽lifter | mediumskintone | weight",
"🏋🏾lifter | medium-darkskintone | weight",
"🏋🏿darkskintone | lifter | weight",
"🚴bicycle | biking | cyclist",
"🚴🏻bicycle | biking | cyclist | lightskintone",
"🚴🏼bicycle | biking | cyclist | medium-lightskintone",
"🚴🏽bicycle | biking | cyclist | mediumskintone",
"🚴🏾bicycle | biking | cyclist | medium-darkskintone",
"🚴🏿bicycle | biking | cyclist | darkskintone",
"🚵bicycle | bicyclist| bike | cyclist | mountain",
"🚵🏻bicycle | bicyclist| bike | cyclist | lightskintone | mountain",
"🚵🏼bicycle | bicyclist| bike | cyclist | medium-lightskintone | mountain",
"🚵🏽bicycle | bicyclist| bike | cyclist | mediumskintone | mountain",
"🚵🏾bicycle | bicyclist| bike | cyclist | medium-darkskintone | mountain",
"🚵🏿bicycle | bicyclist| bike | cyclist | darkskintone | mountain",
"🏎car | racing",
"🏍racing",
"👫couple | hand | hold | man | woman",
"👬couple | Gemini | hand | hold | man | twins | zodiac",
"👭couple | hand | hold | woman",
"💏couple",
"👨‍❤️‍💋‍👨couple | man",
"👩‍❤️‍💋‍👩couple | woman",
"💑couple | love",
"👨‍❤️‍👨couple | love | man",
"👩‍❤️‍👩couple | love | woman",
"👪family",
"👨‍👩‍👧family | girl | man| woman",
"👨‍👩‍👧‍👦boy | family | girl| man | woman",
"👨‍👩‍👦‍👦boy | family | man | woman",
"👨‍👩‍👧‍👧family | girl | man| woman",
"👨‍👨‍👦boy | family | man",
"👨‍👨‍👧family | girl | man",
"👨‍👨‍👧‍👦boy | family | girl| man",
"👨‍👨‍👦‍👦boy | family | man",
"👨‍👨‍👧‍👧family | girl | man",
"👩‍👩‍👦boy | family | woman",
"👩‍👩‍👧family | girl | woman",
"👩‍👩‍👧‍👦boy | family | girl| woman",
"👩‍👩‍👦‍👦boy | family | woman",
"👩‍👩‍👧‍👧family | girl | woman",
"🏻skintone | type1–2",
"🏼skintone | type3",
"🏽skintone | type4",
"🏾skintone | type5",
"🏿skintone | type6",
"💪biceps | comic | flex | muscle",
"💪🏻biceps | comic | flex | lightskintone | muscle",
"💪🏼biceps | comic | flex | medium-lightskintone | muscle",
"💪🏽biceps | comic | flex | mediumskintone | muscle",
"💪🏾biceps | comic | flex | medium-darkskintone | muscle",
"💪🏿biceps | comic | darkskintone | flex | muscle",
"👈backhand | finger | hand | index | point",
"👈🏻backhand | finger | hand | index | lightskintone | point",
"👈🏼backhand | finger | hand | index | medium-lightskintone | point",
"👈🏽backhand | finger | hand | index | mediumskintone | point",
"👈🏾backhand | finger | hand | index | medium-darkskintone | point",
"👈🏿backhand | darkskintone | finger| hand | index | point",
"👉backhand | finger | hand | index | point",
"👉🏻backhand | finger | hand | index | lightskintone | point",
"👉🏼backhand | finger | hand | index | medium-lightskintone | point",
"👉🏽backhand | finger | hand | index | mediumskintone | point",
"👉🏾backhand | finger | hand | index | medium-darkskintone | point",
"👉🏿backhand | darkskintone | finger| hand | index | point",
"☝finger | hand | index | point | up",
"☝🏻finger | hand | index | lightskintone | point | up",
"☝🏼finger | hand | index | medium-lightskintone | point | up",
"☝🏽finger | hand | index | mediumskintone | point | up",
"☝🏾finger | hand | index | medium-darkskintone | point | up",
"☝🏿darkskintone | finger | hand | index | point | up",
"👆backhand | finger | hand | index | point | up",
"👆🏻backhand | finger | hand | index | lightskintone | point | up",
"👆🏼backhand | finger | hand | index | medium-lightskintone | point | up",
"👆🏽backhand | finger | hand | index | mediumskintone | point | up",
"👆🏾backhand | finger | hand | index | medium-darkskintone | point | up",
"👆🏿backhand | darkskintone | finger| hand | index | point | up",
"🖕finger | hand",
"🖕🏻finger | hand | lightskintone",
"🖕🏼finger | hand | medium-lightskintone",
"🖕🏽finger | hand | mediumskintone",
"🖕🏾finger | hand | medium-darkskintone",
"🖕🏿darkskintone | finger | hand",
"👇backhand | down| finger | hand | index | point",
"👇🏻backhand | down| finger | hand | index | lightskintone | point",
"👇🏼backhand | down| finger | hand | index | medium-lightskintone | point",
"👇🏽backhand | down| finger | hand | index | mediumskintone | point",
"👇🏾backhand | down| finger | hand | index | medium-darkskintone | point",
"👇🏿backhand | darkskintone | down| finger | hand | index | point",
"✌hand | v | victory",
"✌🏻hand | lightskintone | v | victory",
"✌🏼hand | medium-lightskintone | v| victory",
"✌🏽hand | mediumskintone | v | victory",
"✌🏾hand | medium-darkskintone | v| victory",
"✌🏿darkskintone | hand | v | victory",
"🤞cross | finger | hand | luck",
"🤞🏻cross | finger | hand | lightskintone | luck",
"🤞🏼cross | finger | hand | luck | medium-lightskintone",
"🤞🏽cross | finger | hand | luck | mediumskintone",
"🤞🏾cross | finger | hand | luck | medium-darkskintone",
"🤞🏿cross | darkskintone | finger | hand | luck",
"🖖finger | hand | spock | vulcan",
"🖖🏻finger | hand | lightskintone | spock | vulcan",
"🖖🏼finger | hand | medium-lightskintone | spock| vulcan",
"🖖🏽finger | hand | mediumskintone | spock | vulcan",
"🖖🏾finger | hand | medium-darkskintone | spock| vulcan",
"🖖🏿darkskintone | finger | hand | spock | vulcan",
"🤘finger | hand | horns | rock-on",
"🤘🏻finger | hand | horns | lightskintone | rock-on",
"🤘🏼finger | hand | horns | medium-lightskintone | rock-on",
"🤘🏽finger | hand | horns | mediumskintone | rock-on",
"🤘🏾finger | hand | horns | medium-darkskintone | rock-on",
"🤘🏿darkskintone | finger | hand | horns | rock-on",
"🤙call | hand",
"🤙🏻call | hand | lightskintone",
"🤙🏼call | hand | medium-lightskintone",
"🤙🏽call | hand | mediumskintone",
"🤙🏾call | hand | medium-darkskintone",
"🤙🏿call | darkskintone | hand",
"🖐finger | hand | splayed",
"🖐🏻finger | hand | lightskintone | splayed",
"🖐🏼finger | hand | medium-lightskintone | splayed",
"🖐🏽finger | hand | mediumskintone | splayed",
"🖐🏾finger | hand | medium-darkskintone | splayed",
"🖐🏿darkskintone | finger | hand | splayed",
"✋hand",
"✋🏻hand | lightskintone",
"✋🏼hand | medium-lightskintone",
"✋🏽hand | mediumskintone",
"✋🏾hand | medium-darkskintone",
"✋🏿darkskintone | hand",
"👌hand | OK",
"👌🏻hand | lightskintone | OK",
"👌🏼hand | medium-lightskintone | OK",
"👌🏽hand | mediumskintone | OK",
"👌🏾hand | medium-darkskintone | OK",
"👌🏿darkskintone | hand | OK",
"👍+1 | hand | thumb | up",
"👍🏻+1 | hand | lightskintone | thumb| up",
"👍🏼+1 | hand | medium-lightskintone | thumb| up",
"👍🏽+1 | hand | mediumskintone | thumb | up",
"👍🏾+1 | hand | medium-darkskintone | thumb| up",
"👍🏿+1 | darkskintone | hand | thumb | up",
"👎-1 | down | hand| thumb",
"👎🏻-1 | down | hand| lightskintone | thumb",
"👎🏼-1 | down | hand| medium-lightskintone | thumb",
"👎🏽-1 | down | hand| mediumskintone | thumb",
"👎🏾-1 | down | hand| medium-darkskintone | thumb",
"👎🏿-1 | darkskintone | down | hand | thumb",
"✊clenched | fist | hand | punch",
"✊🏻clenched | fist | hand | lightskintone | punch",
"✊🏼clenched | fist | hand | medium-lightskintone | punch",
"✊🏽clenched | fist | hand | mediumskintone | punch",
"✊🏾clenched | fist | hand | medium-darkskintone | punch",
"✊🏿clenched | darkskintone | fist | hand | punch",
"👊clenched | fist | hand | punch",
"👊🏻clenched | fist | hand | lightskintone | punch",
"👊🏼clenched | fist | hand | medium-lightskintone | punch",
"👊🏽clenched | fist | hand | mediumskintone | punch",
"👊🏾clenched | fist | hand | medium-darkskintone | punch",
"👊🏿clenched | darkskintone | fist | hand | punch",
"👋hand | wave | waving",
"👋🏻hand | lightskintone | wave | waving",
"👋🏼hand | medium-lightskintone | wave | waving",
"👋🏽hand | mediumskintone | wave| waving",
"👋🏾hand | medium-darkskintone | wave | waving",
"👋🏿darkskintone | hand | wave | waving",
"👏clap | hand",
"👏🏻clap | hand | lightskintone",
"👏🏼clap | hand | medium-lightskintone",
"👏🏽clap | hand | mediumskintone",
"👏🏾clap | hand | medium-darkskintone",
"👏🏿clap | darkskintone | hand",
"✍hand | write",
"✍🏻hand | lightskintone | write",
"✍🏼hand | medium-lightskintone | write",
"✍🏽hand | mediumskintone | write",
"✍🏾hand | medium-darkskintone | write",
"✍🏿darkskintone | hand | write",
"👐hand",
"👐🏻hand | lightskintone",
"👐🏼hand | medium-lightskintone",
"👐🏽hand | mediumskintone",
"👐🏾hand | medium-darkskintone",
"👐🏿darkskintone | hand",
"🙌celebration | gesture | hand | hooray | raised",
"🙌🏻celebration | gesture | hand | hooray | lightskintone | raised",
"🙌🏼celebration | gesture | hand | hooray | medium-lightskintone | raised",
"🙌🏽celebration | gesture | hand | hooray | mediumskintone | raised",
"🙌🏾celebration | gesture | hand | hooray | medium-darkskintone | raised",
"🙌🏿celebration | darkskintone | gesture | hand | hooray | raised",
"🙏ask | bow | folded | gesture | hand | please | pray | thanks",
"🙏🏻ask | bow | folded | gesture | hand | lightskintone | please | pray | thanks",
"🙏🏼ask | bow | folded | gesture | hand | medium-lightskintone | please | pray | thanks",
"🙏🏽ask | bow | folded | gesture | hand | mediumskintone | please | pray | thanks",
"🙏🏾ask | bow | folded | gesture | hand | medium-darkskintone | please | pray | thanks",
"🙏🏿ask | bow | darkskintone | folded| gesture | hand | please | pray | thanks",
"🤝agreement | hand | handshake | meeting | shake",
"🤝🏻agreement | hand | handshake | lightskintone | meeting | shake",
"🤝🏼agreement | hand | handshake | medium-lightskintone | meeting | shake",
"🤝🏽agreement | hand | handshake | mediumskintone | meeting | shake",
"🤝🏾agreement | hand | handshake | medium-darkskintone | meeting | shake",
"🤝🏿agreement | darkskintone | hand | handshake | meeting | shake",
"💅care | cosmetics| manicure | nail | polish",
"💅🏻care | cosmetics| lightskintone | manicure | nail | polish",
"💅🏼care | cosmetics| manicure | medium-lightskintone | nail | polish",
"💅🏽care | cosmetics| manicure | mediumskintone | nail | polish",
"💅🏾care | cosmetics| manicure | medium-darkskintone | nail | polish",
"💅🏿care | cosmetics| darkskintone | manicure | nail | polish",
"👂body",
"👂🏻body | lightskintone",
"👂🏼body | medium-lightskintone",
"👂🏽body | mediumskintone",
"👂🏾body | medium-darkskintone",
"👂🏿body | darkskintone",
"👃body",
"👃🏻body | lightskintone",
"👃🏼body | medium-lightskintone",
"👃🏽body | mediumskintone",
"👃🏾body | medium-darkskintone",
"👃🏿body | darkskintone",
"👣clothing | footprint | print",
"👀eye | face",
"👁body",
"👅body",
"👄lips",
"💋kiss | lips",
"💘arrow | cupid",
"❤heart",
"💓beating | heartbeat | pulsating",
"💔break | broken",
"💕love",
"💖excited | sparkle",
"💗excited | growing| nervous | pulse",
"💙blue",
"💚green",
"💛yellow",
"💜purple",
"🖤black | evil | wicked",
"💝ribbon | valentine",
"💞revolving",
"💟heart",
"❣exclamation | mark | punctuation",
"💌heart | letter | love | mail",
"💤comic | sleep",
"💢angry | comic | mad",
"💣comic",
"💥boom | comic",
"💦comic | splashing | sweat",
"💨comic | dash | running",
"💫comic | star",
"💬balloon | bubble | comic | dialog | speech",
"🗯angry | balloon | bubble | mad",
"💭balloon | bubble | comic | thought",
"🕳hole",
"👓clothing | eye | eyeglasses | eyewear",
"🕶dark | eye | eyewear | glasses",
"👔clothing",
"👕clothing | shirt | tshirt",
"👖clothing | pants | trousers",
"👗clothing",
"👘clothing",
"👙clothing | swim",
"👚clothing | woman",
"👛clothing | coin",
"👜bag | clothing | purse",
"👝bag | clothing | pouch",
"🛍bag | hotel | shopping",
"🎒bag | satchel | school",
"👞clothing | man | shoe",
"👟athletic | clothing| shoe | sneaker",
"👠clothing | heel | shoe | woman",
"👡clothing | sandal| shoe | woman",
"👢boot | clothing | shoe | woman",
"👑clothing | king | queen",
"👒clothing | hat | woman",
"🎩clothing | hat | top | tophat",
"🎓cap | celebration| clothing | graduation | hat",
"⛑aid | cross | face| hat | helmet",
"📿beads | clothing | necklace | prayer| religion",
"💄cosmetics | makeup",
"💍diamond",
"💎diamond | gem | jewel",
"🐵face | monkey",
"🐒monkey",
"🐶dog | face | pet",
"🐕pet",
"🐩dog",
"🐺face | wolf",
"🐱cat | face | pet",
"🐈pet",
"🦁face | Leo | lion | zodiac",
"🐯face | tiger",
"🐅tiger",
"🐆leopard",
"🐴face | horse",
"🐎equestrian | racehorse | racing",
"🦄face | unicorn",
"🐮cow | face",
"🐂bull | Taurus | zodiac",
"🐃buffalo | water",
"🐄cow",
"🐷face | pig",
"🐖sow",
"🐗pig",
"🐽face | nose | pig",
"🐏Aries | sheep | zodiac",
"🐑ewe",
"🐐Capricorn | zodiac",
"🐪dromedary | hump",
"🐫bactrian | camel | hump",
"🐘elephant",
"🐭face | mouse",
"🐁mouse",
"🐀rat",
"🐹face | hamster | pet",
"🐰bunny | face | pet | rabbit",
"🐇bunny | pet",
"🐿chipmunk",
"🐻bear | face",
"🐨bear",
"🐼face | panda",
"🐾feet | paw | print",
"🦃turkey",
"🐔chicken",
"🐓rooster",
"🐣baby | chick | hatching",
"🐤baby | chick",
"🐥baby | chick",
"🐦bird",
"🐧penguin",
"🕊bird | fly | peace",
"🐸face | frog",
"🐊crocodile",
"🐢terrapin | tortoise| turtle",
"🐍bearer | Ophiuchus | serpent | zodiac",
"🐲dragon | face | fairytale",
"🐉fairytale",
"🐳face | spouting | whale",
"🐋whale",
"🐬flipper",
"🐟Pisces | zodiac",
"🐠fish | tropical",
"🐡fish",
"🐙octopus",
"🐚shell | spiral",
"🦀Cancer | zodiac",
"🐌snail",
"🐛insect",
"🐜insect",
"🐝bee | insect",
"🐞beetle | insect | ladybird | ladybug",
"🕷insect",
"🕸spider | web",
"🦂scorpio | Scorpius | zodiac",
"💐flower",
"🌸blossom | cherry| flower",
"💮flower",
"🏵plant",
"🌹flower",
"🥀flower | wilted",
"🌺flower",
"🌻flower | sun",
"🌼flower",
"🌷flower",
"🌱young",
"🌲tree",
"🌳deciduous | shedding | tree",
"🌴palm | tree",
"🌵plant",
"🌾ear | grain | rice",
"🌿leaf",
"☘plant",
"🍀4 | clover | four | leaf",
"🍁falling | leaf | maple",
"🍂falling | leaf",
"🍃blow | flutter | leaf | wind",
"🍇fruit | grape",
"🍈fruit",
"🍉fruit",
"🍊fruit | orange",
"🍋citrus | fruit",
"🍌fruit",
"🍍fruit",
"🍎apple | fruit | red",
"🍏apple | fruit | green",
"🍐fruit",
"🍑fruit",
"🍒cherry | fruit",
"🍓berry | fruit",
"🥝food | fruit | kiwi",
"🍅fruit | vegetable",
"🥑avocado | food | fruit",
"🍆aubergine | vegetable",
"🥔food | potato | vegetable",
"🥕carrot | food | vegetable",
"🌽corn | ear | maize | maze",
"🌶hot | pepper",
"🥒cucumber | food| pickle | vegetable",
"🍄toadstool",
"🥜food | nut | peanut | vegetable",
"🌰plant",
"🍞loaf",
"🥐bread | crescentroll | croissant | food | french",
"🥖baguette | bread| food | french",
"🥞crêpe | food | hotcake | pancake",
"🧀cheese",
"🍖bone | meat",
"🍗bone | chicken | leg | poultry",
"🥓bacon | food | meat",
"🍔burger",
"🍟french | fries",
"🍕cheese | slice",
"🌭frankfurter | hotdog | sausage",
"🌮mexican",
"🌯mexican | wrap",
"🥙falafel | flatbread| food | gyro | kebab | stuffed",
"🥚egg | food",
"🍳egg | frying | pan",
"🥘casserole | food | paella | pan | shallow",
"🍲pot | stew",
"🥗food | green | salad",
"🍿popcorn",
"🍱bento | box",
"🍘cracker | rice",
"🍙ball | Japanese | rice",
"🍚cooked | rice",
"🍛curry | rice",
"🍜bowl | noodle | ramen | steaming",
"🍝pasta",
"🍠potato | roasted | sweet",
"🍢kebab | seafood| skewer | stick",
"🍣sushi",
"🍤fried | prawn | shrimp | tempura",
"🍥cake | fish | pastry | swirl",
"🍡dessert | Japanese | skewer | stick | sweet",
"🍦cream | dessert | ice | icecream | soft | sweet",
"🍧dessert | ice | shaved | sweet",
"🍨cream | dessert | ice | sweet",
"🍩dessert | donut | sweet",
"🍪dessert | sweet",
"🎂birthday | cake | celebration | dessert | pastry | sweet",
"🍰cake | dessert | pastry | slice | sweet",
"🍫bar | chocolate | dessert | sweet",
"🍬dessert | sweet",
"🍭candy | dessert | sweet",
"🍮dessert | pudding | sweet",
"🍯honey | honeypot | pot | sweet",
"🍼baby | bottle | drink | milk",
"🥛drink | glass | milk",
"☕beverage | coffee | drink | hot | steaming | tea",
"🍵beverage | cup | drink | tea | teacup",
"🍶bar | beverage | bottle | cup | drink",
"🍾bar | bottle | cork| drink | popping",
"🍷bar | beverage | drink | glass | wine",
"🍸bar | cocktail | drink | glass",
"🍹bar | drink | tropical",
"🍺bar | beer | drink| mug",
"🍻bar | beer | clink | drink | mug",
"🥂celebrate | clink | drink | glass",
"🥃glass | liquor | shot | tumbler | whisky",
"🍽cooking | fork | knife | plate",
"🍴cooking | fork | knife",
"🥄spoon | tableware",
"🔪cooking | hocho | knife | tool | weapon",
"🏺Aquarius | cooking | drink | jug | tool | weapon | zodiac",
"🌍Africa | earth | Europe | globe | world",
"🌎Americas | earth| globe | world",
"🌏Asia | Australia | earth | globe | world",
"🌐earth | globe | meridians | world",
"🗺map | world",
"🗾Japan | map",
"🏔cold | mountain | snow",
"⛰mountain",
"🌋eruption | mountain",
"🗻fuji | mountain",
"🏕camping",
"🏖beach | umbrella",
"🏜desert",
"🏝desert | island",
"🏞park",
"🏟stadium",
"🏛classical",
"🏗construction",
"🏘house",
"🏙city",
"🏚derelict | house",
"🏠home | house",
"🏡garden | home | house",
"🏢building",
"🏣Japanese | post",
"🏤European | post",
"🏥doctor | medicine",
"🏦building",
"🏨building",
"🏩hotel | love",
"🏪convenience | store",
"🏫building",
"🏬department | store",
"🏭building",
"🏯castle | Japanese",
"🏰European",
"💒chapel | romance",
"🗼Tokyo | tower",
"🗽liberty | statue",
"⛪Christian | cross| religion",
"🕌islam | Muslim | religion",
"🕍Jew | Jewish | religion | temple",
"⛩religion | shinto | shrine",
"🕋islam | Muslim | religion",
"⛲fountain",
"⛺camping",
"🌁fog",
"🌃night | star",
"🌄morning | mountain | sun | sunrise",
"🌅morning | sun",
"🌆city | dusk | evening | landscape | sun | sunset",
"🌇dusk | sun",
"🌉bridge | night",
"♨hot | hotsprings | springs | steaming",
"🌌space",
"🎠carousel | horse",
"🎡amusementpark| ferris | wheel",
"🎢amusementpark| coaster | roller",
"💈barber | haircut | pole",
"🎪circus | tent",
"🎭art | mask | performing | theater | theatre",
"🖼art | frame | museum | painting | picture",
"🎨art | museum | painting | palette",
"🎰game | slot",
"🚂engine | railway | steam | train",
"🚃car | electric | railway | train | tram | trolleybus",
"🚄railway | shinkansen | speed | train",
"🚅bullet | railway | shinkansen | speed | train",
"🚆railway",
"🚇subway",
"🚈railway",
"🚉railway | train",
"🚊trolleybus",
"🚝vehicle",
"🚞car | mountain | railway",
"🚋car | tram | trolleybus",
"🚌vehicle",
"🚍bus | oncoming",
"🚎bus | tram | trolley",
"🚐bus",
"🚑vehicle",
"🚒engine | fire | truck",
"🚓car | patrol | police",
"🚔car | oncoming | police",
"🚕vehicle",
"🚖oncoming | taxi",
"🚗car",
"🚘automobile | car| oncoming",
"🚙recreational | sportutility",
"🚚delivery | truck",
"🚛lorry | semi | truck",
"🚜vehicle",
"🚲bike",
"🛴kick | scooter",
"🛵motor | scooter",
"🚏bus | busstop | stop",
"🛣highway | road",
"🛤railway | train",
"⛽fuel | fuelpump | gas | pump | station",
"🚨beacon | car | light | police | revolving",
"🚥light | signal | traffic",
"🚦light | signal | traffic",
"🚧barrier",
"🛑octagonal | sign | stop",
"⚓ship | tool",
"⛵boat | resort | sea | yacht",
"🛶boat | canoe",
"🚤boat",
"🛳passenger | ship",
"⛴boat | passenger",
"🛥boat | motorboat",
"🚢boat | passenger",
"✈aeroplane | airplane",
"🛩aeroplane | airplane",
"🛫aeroplane | airplane | check-in | departure | departures",
"🛬aeroplane | airplane | arrivals| arriving | landing",
"💺chair",
"🚁vehicle",
"🚟railway | suspension",
"🚠cable | gondola | mountain",
"🚡aerial | cable | car | gondola | tramway",
"🚀space",
"🛰space",
"🛎bell | bellhop | hotel",
"🚪door",
"🛌hotel | sleep",
"🛏hotel | sleep",
"🛋couch | hotel | lamp",
"🚽toilet",
"🚿water",
"🛀bath | bathtub",
"🛀🏻bath | bathtub | lightskintone",
"🛀🏼bath | bathtub | medium-lightskintone",
"🛀🏽bath | bathtub | mediumskintone",
"🛀🏾bath | bathtub | medium-darkskintone",
"🛀🏿bath | bathtub | darkskintone",
"🛁bath",
"⌛sand | timer",
"⏳hourglass | sand| timer",
"⌚clock",
"⏰alarm | clock",
"⏱clock",
"⏲clock | timer",
"🕰clock",
"🕛00 | 12 | 12:00 | clock | o’clock | twelve",
"🕧12 | 12:30 | 30 | clock | thirty | twelve",
"🕐00 | 1 | 1:00 | clock | o’clock | one",
"🕜1 | 1:30 | 30 | clock | one | thirty",
"🕑00 | 2 | 2:00 | clock | o’clock | two",
"🕝2 | 2:30 | 30 | clock | thirty | two",
"🕒00 | 3 | 3:00 | clock | o’clock | three",
"🕞3 | 3:30 | 30 | clock | thirty | three",
"🕓00 | 4 | 4:00 | clock | four | o’clock",
"🕟30 | 4 | 4:30 | clock | four | thirty",
"🕔00 | 5 | 5:00 | clock | five | o’clock",
"🕠30 | 5 | 5:30 | clock | five | thirty",
"🕕00 | 6 | 6:00 | clock | o’clock | six",
"🕡30 | 6 | 6:30 | clock | six | thirty",
"🕖00 | 7 | 7:00 | clock | o’clock | seven",
"🕢30 | 7 | 7:30 | clock | seven | thirty",
"🕗00 | 8 | 8:00 | clock | eight | o’clock",
"🕣30 | 8 | 8:30 | clock | eight | thirty",
"🕘00 | 9 | 9:00 | clock | nine | o’clock",
"🕤30 | 9 | 9:30 | clock | nine | thirty",
"🕙00 | 10 | 10:00 | clock | o’clock | ten",
"🕥10 | 10:30 | 30 | clock | ten | thirty",
"🕚00 | 11 | 11:00 | clock | eleven | o’clock",
"🕦11 | 11:30 | 30 | clock | eleven | thirty",
"🌑dark | moon",
"🌒crescent | moon| waxing",
"🌓moon | quarter",
"🌔gibbous | moon | waxing",
"🌕full | moon",
"🌖gibbous | moon | waning",
"🌗moon | quarter",
"🌘crescent | moon| waning",
"🌙crescent | moon",
"🌚face | moon",
"🌛face | moon | quarter",
"🌜face | moon | quarter",
"🌡weather",
"☀bright | rays | sunny",
"🌝bright | face | full| moon",
"🌞bright | face | sun",
"⭐star",
"🌟glittery | glow | shining | sparkle| star",
"🌠falling | shooting| star",
"☁weather",
"⛅cloud | sun",
"⛈cloud | rain | thunder",
"🌤cloud | sun",
"🌥cloud | sun",
"🌦cloud | rain | sun",
"🌧cloud | rain",
"🌨cloud | cold | snow",
"🌩cloud | lightning",
"🌪cloud | whirlwind",
"🌫cloud",
"🌬blow | cloud | face | wind",
"🌀dizzy | twister | typhoon",
"🌈rain",
"🌂clothing | rain | umbrella",
"☂clothing | rain",
"☔clothing | drop | rain | umbrella",
"⛱rain | sun | umbrella",
"⚡danger | electric| electricity | lightning | voltage | zap",
"❄cold | snow",
"☃cold | snow",
"⛄cold | snow | snowman",
"☄space",
"🔥flame | tool",
"💧cold | comic | drop | sweat",
"🌊ocean | water | wave",
"🎃celebration | halloween | jack| lantern",
"🎄celebration | Christmas | tree",
"🎆celebration",
"🎇celebration | fireworks | sparkle",
"✨sparkle | star",
"🎈celebration",
"🎉celebration | party | popper | tada",
"🎊ball | celebration| confetti",
"🎋banner | celebration | Japanese | tree",
"🎍bamboo | celebration | Japanese | pine",
"🎎celebration | doll| festival | Japanese",
"🎏carp | celebration | streamer",
"🎐bell | celebration| chime | wind",
"🎑celebration | ceremony | moon",
"🎀celebration",
"🎁box | celebration| gift | present | wrapped",
"🎗celebration | reminder | ribbon",
"🎟admission | ticket",
"🎫admission",
"🎖celebration | medal | military",
"🏆prize",
"🏅medal",
"🥇first | gold | medal",
"🥈medal | second | silver",
"🥉bronze | medal | third",
"⚽ball | football | soccer",
"⚾ball",
"🏀ball | hoop",
"🏐ball | game",
"🏈american | ball | football",
"🏉ball | football | rugby",
"🎾ball | racquet",
"🎱8 | 8ball | ball | billiard | eight | game",
"🎳ball | game",
"🏏ball | bat | game",
"🏑ball | field | game| hockey | stick",
"🏒game | hockey | ice | puck | stick",
"🏓ball | bat | game | paddle | pingpong | tabletennis",
"🏸birdie | game | racquet | shuttlecock",
"🥊boxing | glove",
"🥋judo | karate | martialarts | taekwondo | uniform",
"🥅goal | net",
"🎯bull | bullseye | dart | eye | game| hit | target",
"⛳golf | hole",
"⛸ice | skate",
"🎣fish | pole",
"🎽athletics | running | sash | shirt",
"🎿ski | snow",
"🎮controller | game",
"🕹game | videogame",
"🎲dice | die | game",
"♠card | game",
"♥card | game",
"♦card | game",
"♣card | game",
"🃏card | game | wildcard",
"🀄game | mahjong| red",
"🎴card | flower | game | Japanese | playing",
"🔇mute | quiet | silent | speaker",
"🔈soft",
"🔉medium",
"🔊loud",
"📢loud | publicaddress",
"📣cheering",
"📯horn | post | postal",
"🔔bell",
"🔕bell | forbidden | mute | no | not | prohibited | quiet| silent",
"🎼music | score",
"🎵music | note",
"🎶music | note | notes",
"🎙mic | microphone| music | studio",
"🎚level | music | slider",
"🎛control | knobs | music",
"🎤karaoke | mic",
"🎧earbud",
"📻video",
"🎷instrument | music | sax",
"🎸instrument | music",
"🎹instrument | keyboard | music| piano",
"🎺instrument | music",
"🎻instrument | music",
"🥁drum | drumsticks | music",
"📱cell | mobile | phone | telephone",
"📲arrow | call | cell| mobile | phone | receive | telephone",
"☎phone",
"📞phone | receiver| telephone",
"📟pager",
"📠fax",
"🔋battery",
"🔌electric | electricity | plug",
"💻computer | pc | personal",
"🖥computer | desktop",
"🖨computer",
"⌨computer",
"🖱computer",
"🖲computer",
"💽computer | disk | minidisk | optical",
"💾computer | disk | floppy",
"💿cd | computer | disk | optical",
"📀blu-ray | computer | disk | dvd | optical",
"🎥camera | cinema| movie",
"🎞cinema | film | frames | movie",
"📽cinema | film | movie | projector| video",
"🎬clapper | movie",
"📺tv | video",
"📷video",
"📸camera | flash | video",
"📹camera | video",
"📼tape | vhs | video",
"🔍glass | magnifying | search | tool",
"🔎glass | magnifying | search | tool",
"🔬science | tool",
"🔭science | tool",
"📡antenna | dish | satellite",
"🕯light",
"💡bulb | comic | electric | idea | light",
"🔦electric | light | tool | torch",
"🏮bar | Japanese | lantern | light | red",
"📔book | cover | decorated | notebook",
"📕book | closed",
"📖book",
"📗book | green",
"📘blue | book",
"📙book | orange",
"📚book",
"📓notebook",
"📒notebook",
"📃curl | document | page",
"📜paper",
"📄document | page",
"📰news | paper",
"🗞news | newspaper | paper | rolled",
"📑bookmark | mark| marker | tabs",
"🔖mark",
"🏷label",
"💰bag | dollar | money | moneybag",
"💴bank | banknote| bill | currency | money | note | yen",
"💵bank | banknote| bill | currency | dollar | money | note",
"💶bank | banknote| bill | currency | euro | money | note",
"💷bank | banknote| bill | currency | money | note | pound",
"💸bank | banknote| bill | dollar | fly | money | note | wings",
"💳bank | card | credit | money",
"💹bank | chart | currency | graph| growth | market| money | rise | trend | upward | yen",
"💱bank | currency | exchange | money",
"💲currency | dollar| money",
"✉email | letter",
"📧email | letter | mail",
"📨e-mail | email | envelope | incoming | letter | mail | receive",
"📩arrow | down | e-mail | email | envelope | letter| mail | outgoing | sent",
"📤box | letter | mail| outbox | sent | tray",
"📥box | inbox | letter | mail | receive | tray",
"📦box | parcel",
"📫closed | mail | mailbox | postbox",
"📪closed | lowered| mail | mailbox | postbox",
"📬mail | mailbox | postbox",
"📭lowered | mail | mailbox | postbox",
"📮mail | mailbox",
"🗳ballot | box",
"✏pencil",
"✒nib | pen",
"🖋fountain | pen",
"🖊ballpoint",
"🖌painting",
"🖍crayon",
"📝pencil",
"💼briefcase",
"📁file | folder",
"📂file | folder",
"🗂card | dividers | index",
"📅date",
"📆calendar",
"🗒note | pad | spiral",
"🗓calendar | pad | spiral",
"📇card | index | rolodex",
"📈chart | graph | growth | trend | upward",
"📉chart | down | graph | trend",
"📊bar | chart | graph",
"📋clipboard",
"📌pin",
"📍pin | pushpin",
"📎paperclip",
"🖇link | paperclip",
"📏ruler | straightedge",
"📐ruler | set | triangle",
"✂cutting | tool",
"🗃box | card | file",
"🗄cabinet | file | filing",
"🗑wastebasket",
"🔒closed",
"🔓lock | unlock",
"🔏ink | lock | nib | pen | privacy",
"🔐closed | key | lock | secure",
"🔑lock | password",
"🗝clue | key | lock | old",
"🔨tool",
"⛏mining | tool",
"⚒hammer | pick | tool",
"🛠hammer | spanner | tool | wrench",
"🗡knife | weapon",
"⚔crossed | swords| weapon",
"🔫gun | handgun | revolver | tool | weapon",
"🏹archer | archery | arrow | bow | Sagittarius | tool| weapon | zodiac",
"🛡weapon",
"🔧spanner | tool | wrench",
"🔩bolt | nut | tool",
"⚙tool",
"🗜compress | tool | vice",
"⚗chemistry | tool",
"⚖balance | justice| Libra | scales | tool | weight | zodiac",
"🔗link",
"⛓chain",
"💉doctor | medicine| needle | shot | sick | tool",
"💊doctor | medicine| sick",
"🚬smoking",
"⚰death",
"⚱ashes | death | funeral | urn",
"🗿face | moyai | statue",
"🛢drum | oil",
"🔮ball | crystal | fairytale | fantasy | fortune| tool",
"🛒cart | shopping | trolley",
"🏧atm | automated| bank | teller",
"🚮litter | litterbin",
"🚰drinking | potable| water",
"♿access",
"🚹lavatory | man | restroom | wc",
"🚺lavatory | restroom | wc | woman",
"🚻lavatory | restroom | WC",
"🚼baby | changing",
"🚾closet | lavatory | restroom | water| wc",
"🛂control | passport",
"🛃customs",
"🛄baggage | claim",
"🛅baggage | locker| luggage",
"⚠warning",
"🚸child | crossing | pedestrian | traffic",
"⛔entry | forbidden| no | not | prohibited | traffic",
"🚫entry | forbidden| no | not",
"🚳bicycle | bike | forbidden | no | not | prohibited",
"🚭forbidden | no | not | prohibited | smoking",
"🚯forbidden | litter | no | not | prohibited",
"🚱non-drinking | non-potable | water",
"🚷forbidden | no | not | pedestrian | prohibited",
"📵cell | forbidden | mobile | no | not | phone | prohibited | telephone",
"🔞18 | agerestriction | eighteen | forbidden | no | not | prohibited | underage",
"☢radioactive | sign",
"☣biohazard | sign",
"⬆arrow | cardinal | direction | north",
"↗arrow | direction| intercardinal | northeast",
"➡arrow | cardinal | direction | east",
"↘arrow | direction| intercardinal | southeast",
"⬇arrow | cardinal | direction | down | south",
"↙arrow | direction| intercardinal | southwest",
"⬅arrow | cardinal | direction | west",
"↖arrow | direction| intercardinal | northwest",
"↕arrow",
"↔arrow",
"↩arrow",
"↪arrow",
"⤴arrow",
"⤵arrow | down",
"🔃arrow | clockwise| reload",
"🔄anticlockwise | arrow | counterclockwise| withershins",
"🔙arrow | back",
"🔚arrow | end",
"🔛arrow | mark | on",
"🔜arrow | soon",
"🔝arrow | top | up",
"🛐religion | worship",
"⚛atheist | atom",
"🕉Hindu | religion",
"✡David | Jew | Jewish | religion| star",
"🕎candelabrum | candlestick | religion",
"🔯fortune | star",
"♈ram | zodiac",
"♉bull | ox | zodiac",
"♊twins | zodiac",
"♋crab | zodiac",
"♌lion | zodiac",
"♍zodiac",
"♎balance | justice| scales | zodiac",
"♏scorpio | scorpion | zodiac",
"♐archer | zodiac",
"♑goat | zodiac",
"♒bearer | water | zodiac",
"♓fish | zodiac",
"⛎bearer | serpent | snake | zodiac",
"🔀arrow | crossed",
"🔁arrow | clockwise| repeat",
"🔂arrow | clockwise| once",
"▶arrow | play | right | triangle",
"⏩arrow | double | fast | forward",
"⏭arrow | nextscene | nexttrack | triangle",
"⏯arrow | pause | play | right | triangle",
"◀arrow | left | reverse | triangle",
"⏪arrow | double | rewind",
"⏮arrow | previousscene | previoustrack | triangle",
"🔼arrow | button | red",
"⏫arrow | double",
"🔽arrow | button | down | red",
"⏬arrow | double | down",
"⏸bar | double | pause | vertical",
"⏹square | stop",
"⏺circle | record",
"🎦camera | film | movie",
"🔅brightness | dim | low",
"🔆bright | brightness",
"📶antenna | bar | cell | mobile | phone | signal | telephone",
"📳cell | mobile | mode | phone | telephone | vibration",
"📴cell | mobile | off| phone | telephone",
"♻recycle",
"📛badge | name",
"⚜fleur-de-lis",
"🔰beginner | chevron | green | Japanese | leaf | tool | yellow",
"🔱anchor | emblem| ship | tool | trident",
"⭕circle | o",
"✅check | mark",
"☑ballot | box | check",
"✔check | mark",
"✖cancel | multiplication | multiply | x",
"❌cancel | mark | multiplication | multiply | x",
"❎mark | square",
"➕math | plus",
"➖math | minus",
"➗division | math",
"➰curl | loop",
"➿curl | double | loop",
"〽mark | part",
"✳asterisk",
"✴star",
"❇sparkle",
"‼bangbang | exclamation | mark | punctuation",
"⁉exclamation | interrobang | mark | punctuation | question",
"❓mark | punctuation | question",
"❔mark | outlined | punctuation | question",
"❕exclamation | mark | outlined | punctuation",
"❗exclamation | mark | punctuation",
"〰dash | punctuation | wavy",
"#️⃣keycap",
"*️⃣keycap",
"0️⃣keycap",
"1️⃣keycap",
"2️⃣keycap",
"3️⃣keycap",
"4️⃣keycap",
"5️⃣keycap",
"6️⃣keycap",
"7️⃣keycap",
"8️⃣keycap",
"9️⃣keycap",
"🔟keycap10",
"💯100 | full | hundred | score",
"🔠ABCD | input | latin | letters | uppercase",
"🔡abcd | input | latin | letters | lowercase",
"🔢1234 | input | numbers",
"🔣〒♪&% | input",
"🔤abc | alphabet | input | latin | letters",
"🅰a | bloodtype",
"🆎ab | bloodtype",
"🅱b | bloodtype",
"🆑cl",
"🆒cool",
"🆓free",
"ℹi | information",
"🆔id | identity",
"Ⓜcircle | m",
"🆕new",
"🆖ng",
"🅾bloodtype | o",
"🆗OK",
"🅿parking",
"🆘help | sos",
"🆙mark | up",
"🆚versus | vs",
"🈁“here” | Japanese | katakana | ココ",
"🈂“servicecharge”| Japanese | katakana | サ",
"🈷“monthlyamount” | ideograph | Japanese | 月",
"🈶“notfreeofcharge” | ideograph | Japanese | 有",
"🈯“reserved” | ideograph | Japanese | 指",
"🉐“bargain” | ideograph | Japanese | 得",
"🈹“discount” | ideograph | Japanese | 割",
"🈚“freeofcharge” | ideograph | Japanese | 無",
"🈲“prohibited” | ideograph | Japanese | 禁",
"🉑“acceptable” | ideograph | Japanese | 可",
"🈸“application” | ideograph | Japanese | 申",
"🈴“passinggrade” | ideograph | Japanese | 合",
"🈳“vacancy” | ideograph | Japanese | 空",
"㊗“congratulations”| ideograph | Japanese | 祝",
"㊙“secret” | ideograph | Japanese | 秘",
"🈵“novacancy” | ideograph | Japanese | 満",
"▪geometric | square",
"▫geometric | square",
"◻geometric | square",
"◼geometric | square",
"◽geometric | square",
"◾geometric | square",
"⬛geometric | square",
"⬜geometric | square",
"🔶diamond | geometric | orange",
"🔷blue | diamond | geometric",
"🔸diamond | geometric | orange",
"🔹blue | diamond | geometric",
"🔺geometric | red",
"🔻down | geometric| red",
"💠comic | diamond| geometric | inside",
"🔘button | geometric | radio",
"🔲button | geometric | square",
"🔳button | geometric | outlined | square",
"⚪circle | geometric",
"⚫circle | geometric",
"🔴circle | geometric| red",
"🔵blue | circle | geometric",
"🏁checkered | chequered | racing",
"🚩post",
"🎌celebration | cross | crossed | Japanese",
"🌨🐎🐎=🎅🎁💨christmas",
"🎁🎄🎁👨‍👩‍👧‍👦✨christmas",
"🐎🐎👶📤👫🏠🕵👳👴🌟christmas",
"🍾🎄🎁👨‍👩‍👧‍👦🍗🍖🍽christmas",
"🌨🎁🎄🎅☃️christmas",
"✏️🍍🍎✏️penpineappleapplepen |ppap",
"✏️🍍🕴🍎✏️penpineappleapplepen |ppap",
"🔫🆗💵☝️👴🇺🇸🚧🇲🇽donaldtrump",
"✡️🕯🔱🕯🕯🍩🎲-hanukkah"

];
