var list = [
{ label: '🌨🐎🐎=🎅🎁💨 merry christmas', value: '🌨🐎🐎=🎅🎁💨' },
{ label: '🎁🎄🎁👨‍👩‍👧‍👦✨ merry christmas', value: '🎁🎄🎁👨‍👩‍👧‍👦✨' },
{ label: '🐎🐎👶📤 👫🏠🕵👳👴🌟 merry christmas', value: '🐎🐎👶📤 👫🏠🕵👳👴🌟' },
{ label: '🍾🎄🎁👨‍👩‍👧‍👦🍗🍖🍽 merry christmas', value: '🍾🎄🎁👨‍👩‍👧‍👦🍗🍖🍽' },
{ label: '🌨🎁🎄🎅☃️ merry christmas', value: '🌨🎁🎄🎅☃️' },
{ label: '✏️🍍🍎✏️pen pineapple apple pen | ppap', value: '✏️🍍🍎✏️' },
{ label: '✏️🍍🕴🍎✏️pen pineapple apple pen | ppap', value: '✏️🍍🕴🍎✏️' },
{ label: '🔫🆗💵☝️👴🇺🇸🚧🇲🇽donald trump', value: '🔫🆗💵☝️👴🇺🇸🚧🇲🇽' },
{ label: '✡️🕯🔱🕯🕯🍩🎲-hanukkah', value: '✡️🕯🔱🕯🕯🍩🎲-' },
{ label: '❤️❣️💨love | heart', value: '❤️❣️💨' },
{ label: '❤️💛💚💙💜✨love | heart', value: '❤️💛💚💙💜✨' },
{ label: '💓💞💕✨love | heart', value: '💓💞💕✨' },
{ label: '💖💗💕彡love | heart', value: '💖💗💕彡' },
{ label: '😘💗🤗xoxo | kiss and hug', value: '😘💗🤗' },
{ label: '🤐👈‼️shut up', value: '🤐👈‼️' },
{ label: '🖕👉😵fuck you', value: '🖕👉😵' },
{ label: '☄️🏄  🏀彡  🏄‍彡Quidditch', value: '☄️🏄  🏀彡  🏄‍彡' },
{ label: '🙂📘 👍facebook', value: '🙂📘 👍' },
{ label: '⚽️✨🏆🌐world cup', value: '⚽️✨🏆🌐' },
{ label: '🏁🏎🏎彡 🏎🏎彡formula 1 | f1', value: '🏁🏎🏎彡 🏎🏎彡' },
{ label: '👯📲👀⌛️▶️💥👻✨snap chat', value: '👯📲👀⌛️▶️💥👻✨' },
{ label: '📲🌚🔄🌝🌨✨snow app', value: '📲🌚🔄🌝🌨✨' },
{ label: '😀face | grin', value: '😀' },
{ label: '😁eye | face | grin | smile', value: '😁' },
{ label: '😂face | joy | laugh| tear', value: '😂' },
{ label: '😃face | mouth | smile', value: '😃' },
{ label: '😄eye | face | mouth | smile', value: '😄' },
{ label: '😅cold | face | smile | sweat', value: '😅' },
{ label: '😆face | laugh | mouth | satisfied | smile', value: '😆' },
{ label: '😉face | wink', value: '😉' },
{ label: '😊blush | eye | face| smile', value: '😊' },
{ label: '😋delicious | face | savouring | smile| um | yum', value: '😋' },
{ label: '😎bright | cool | eye| eyewear | face | glasses | smile | sun | sunglasses', value: '😎' },
{ label: '😍eye | face | love | smile', value: '😍' },
{ label: '😘face | kiss', value: '😘' },
{ label: '😗face | kiss', value: '😗' },
{ label: '😙eye | face | kiss | smile', value: '😙' },
{ label: '😚closed | eye | face | kiss', value: '😚' },
{ label: '☺face | outlined | relaxed | smile', value: '☺' },
{ label: '🙂face | smile', value: '🙂' },
{ label: '🤗face | hug | hugging', value: '🤗' },
{ label: '🤔face | thinking', value: '🤔' },
{ label: '😐deadpan | face | neutral', value: '😐' },
{ label: '😑expressionless | face | inexpressive | unexpressive', value: '😑' },
{ label: '😶face | mouth | quiet | silent', value: '😶' },
{ label: '🙄eyes | face | rolling', value: '🙄' },
{ label: '😏face | smirk', value: '😏' },
{ label: '😣face | persevere', value: '😣' },
{ label: '😥disappointed | face | relieved | whew', value: '😥' },
{ label: '😮face | mouth | sympathy', value: '😮' },
{ label: '🤐face | mouth | zipper', value: '🤐' },
{ label: '😯face | hushed | stunned | surprised', value: '😯' },
{ label: '😪face | sleep', value: '😪' },
{ label: '😫face | tired', value: '😫' },
{ label: '😴face | sleep | zzz', value: '😴' },
{ label: '😌face | relieved', value: '😌' },
{ label: '🤓face | geek | nerd', value: '🤓' },
{ label: '😛face | tongue', value: '😛' },
{ label: '😜eye | face | joke | tongue | wink', value: '😜' },
{ label: '😝eye | face | horrible | taste | tongue', value: '😝' },
{ label: '🤤drooling | face', value: '🤤' },
{ label: '😒face | unamused| unhappy', value: '😒' },
{ label: '😓cold | face | sweat', value: '😓' },
{ label: '😔dejected | face | pensive', value: '😔' },
{ label: '😕confused | face', value: '😕' },
{ label: '🙃face | upside-down', value: '🙃' },
{ label: '🤑face | money | mouth', value: '🤑' },
{ label: '😲astonished | face| shocked | totally', value: '😲' },
{ label: '☹face | frown', value: '☹' },
{ label: '🙁face | frown', value: '🙁' },
{ label: '😖confounded | face', value: '😖' },
{ label: '😞disappointed | face', value: '😞' },
{ label: '😟face | worried', value: '😟' },
{ label: '😤face | triumph | won', value: '😤' },
{ label: '😢cry | face | sad | tear', value: '😢' },
{ label: '😭cry | face | sad | sob | tear', value: '😭' },
{ label: '😦face | frown | mouth', value: '😦' },
{ label: '😧anguished | face', value: '😧' },
{ label: '😨face | fear | fearful | scared', value: '😨' },
{ label: '😩face | tired | weary', value: '😩' },
{ label: '😬face | grimace', value: '😬' },
{ label: '😰blue | cold | face| mouth | rushed | sweat', value: '😰' },
{ label: '😱face | fear | fearful | munch | scared | scream', value: '😱' },
{ label: '😳dazed | face | flushed', value: '😳' },
{ label: '😵dizzy | face', value: '😵' },
{ label: '😡angry | face | mad | pouting | rage | red', value: '😡' },
{ label: '😠angry | face | mad', value: '😠' },
{ label: '😇angel | face | fairy tale | fantasy | halo | innocent | smile', value: '😇' },
{ label: '🤠cowboy | cowgirl| face | hat', value: '🤠' },
{ label: '🤡clown | face', value: '🤡' },
{ label: '🤥face | lie | pinocchio', value: '🤥' },
{ label: '😷cold | doctor | face | mask | medicine | sick', value: '😷' },
{ label: '🤒face | ill | sick | thermometer', value: '🤒' },
{ label: '🤕bandage | face | hurt | injury', value: '🤕' },
{ label: '🤢face | nauseated| vomit', value: '🤢' },
{ label: '🤧face | gesundheit| sneeze', value: '🤧' },
{ label: '😈face | fairy tale | fantasy | horns | smile', value: '😈' },
{ label: '👿demon | devil | face | fairy tale | fantasy | imp', value: '👿' },
{ label: '👹creature | face | fairy tale | fantasy | Japanese | monster', value: '👹' },
{ label: '👺creature | face | fairy tale | fantasy | Japanese | monster', value: '👺' },
{ label: '💀death | face | fairy tale | monster', value: '💀' },
{ label: '☠crossbones | death | face | monster | skull', value: '☠' },
{ label: '👻creature | face | fairy tale | fantasy | monster', value: '👻' },
{ label: '👽creature | extraterrestrial | face | fairy tale | fantasy | monster | ufo', value: '👽' },
{ label: '👾alien | creature | extraterrestrial | face | fairy tale | fantasy | monster | ufo', value: '👾' },
{ label: '🤖face | monster | robot', value: '🤖' },
{ label: '💩comic | dung | face | monster | poo | poop', value: '💩' },
{ label: '😺cat | face | mouth | smile', value: '😺' },
{ label: '😸cat | eye | face | grin | smile', value: '😸' },
{ label: '😹cat | face | joy | tear', value: '😹' },
{ label: '😻cat | eye | face | love | smile', value: '😻' },
{ label: '😼cat | face | ironic| smile | wry', value: '😼' },
{ label: '😽cat | eye | face | kiss', value: '😽' },
{ label: '🙀cat | face | oh | surprised | weary', value: '🙀' },
{ label: '😿cat | cry | face | sad | tear', value: '😿' },
{ label: '😾cat | face | pouting', value: '😾' },
{ label: '🙈evil | face | forbidden | gesture | monkey | no | not | prohibited | see', value: '🙈' },
{ label: '🙉evil | face | forbidden | gesture | hear | monkey | no | not | prohibited', value: '🙉' },
{ label: '🙊evil | face | forbidden | gesture | monkey | no | not | prohibited | speak', value: '🙊' },
{ label: '👦boy | young', value: '👦' },
{ label: '👦🏻boy | light skin tone | young', value: '👦🏻' },
{ label: '👦🏼boy | medium-light skin tone | young', value: '👦🏼' },
{ label: '👦🏽boy | medium skin tone | young', value: '👦🏽' },
{ label: '👦🏾boy | medium-dark skin tone | young', value: '👦🏾' },
{ label: '👦🏿boy | dark skin tone | young', value: '👦🏿' },
{ label: '👧Virgo | young | zodiac', value: '👧' },
{ label: '👧🏻light skin tone | Virgo | young | zodiac', value: '👧🏻' },
{ label: '👧🏼medium-light skin tone | Virgo| young | zodiac', value: '👧🏼' },
{ label: '👧🏽medium skin tone | Virgo | young | zodiac', value: '👧🏽' },
{ label: '👧🏾medium-dark skin tone | Virgo| young | zodiac', value: '👧🏾' },
{ label: '👧🏿dark skin tone | Virgo | young | zodiac', value: '👧🏿' },
{ label: '👨man', value: '👨' },
{ label: '👨🏻light skin tone | man', value: '👨🏻' },
{ label: '👨🏼man | medium-light skin tone', value: '👨🏼' },
{ label: '👨🏽man | medium skin tone', value: '👨🏽' },
{ label: '👨🏾man | medium-dark skin tone', value: '👨🏾' },
{ label: '👨🏿dark skin tone | man', value: '👨🏿' },
{ label: '👩woman', value: '👩' },
{ label: '👩🏻light skin tone | woman', value: '👩🏻' },
{ label: '👩🏼medium-light skin tone | woman', value: '👩🏼' },
{ label: '👩🏽medium skin tone | woman', value: '👩🏽' },
{ label: '👩🏾medium-dark skin tone | woman', value: '👩🏾' },
{ label: '👩🏿dark skin tone | woman', value: '👩🏿' },
{ label: '👴man | old', value: '👴' },
{ label: '👴🏻light skin tone | man | old', value: '👴🏻' },
{ label: '👴🏼man | medium-light skin tone | old', value: '👴🏼' },
{ label: '👴🏽man | medium skin tone | old', value: '👴🏽' },
{ label: '👴🏾man | medium-dark skin tone | old', value: '👴🏾' },
{ label: '👴🏿dark skin tone | man | old', value: '👴🏿' },
{ label: '👵old | woman', value: '👵' },
{ label: '👵🏻light skin tone | old | woman', value: '👵🏻' },
{ label: '👵🏼medium-light skin tone | old | woman', value: '👵🏼' },
{ label: '👵🏽medium skin tone | old | woman', value: '👵🏽' },
{ label: '👵🏾medium-dark skin tone | old | woman', value: '👵🏾' },
{ label: '👵🏿dark skin tone | old | woman', value: '👵🏿' },
{ label: '👶baby | young', value: '👶' },
{ label: '👶🏻baby | light skin tone | young', value: '👶🏻' },
{ label: '👶🏼baby | medium-light skin tone | young', value: '👶🏼' },
{ label: '👶🏽baby | medium skin tone | young', value: '👶🏽' },
{ label: '👶🏾baby | medium-dark skin tone | young', value: '👶🏾' },
{ label: '👶🏿baby | dark skin tone | young', value: '👶🏿' },
{ label: '👼angel | baby | face | fairy tale | fantasy', value: '👼' },
{ label: '👼🏻angel | baby | face | fairy tale | fantasy | light skin tone', value: '👼🏻' },
{ label: '👼🏼angel | baby | face | fairy tale | fantasy | medium-light skin tone', value: '👼🏼' },
{ label: '👼🏽angel | baby | face | fairy tale | fantasy | medium skin tone', value: '👼🏽' },
{ label: '👼🏾angel | baby | face | fairy tale | fantasy | medium-dark skin tone', value: '👼🏾' },
{ label: '👼🏿angel | baby | dark skin tone | face | fairy tale | fantasy', value: '👼🏿' },
{ label: '👮cop | officer | police', value: '👮' },
{ label: '👮🏻cop | light skin tone | officer | police', value: '👮🏻' },
{ label: '👮🏼cop | medium-light skin tone | officer | police', value: '👮🏼' },
{ label: '👮🏽cop | medium skin tone | officer| police', value: '👮🏽' },
{ label: '👮🏾cop | medium-dark skin tone | officer | police', value: '👮🏾' },
{ label: '👮🏿cop | dark skin tone | officer | police', value: '👮🏿' },
{ label: '🕵detective | sleuth| spy', value: '🕵' },
{ label: '🕵🏻detective | light skin tone | sleuth| spy', value: '🕵🏻' },
{ label: '🕵🏼detective | medium-light skin tone | sleuth| spy', value: '🕵🏼' },
{ label: '🕵🏽detective | medium skin tone | sleuth | spy', value: '🕵🏽' },
{ label: '🕵🏾detective | medium-dark skin tone | sleuth| spy', value: '🕵🏾' },
{ label: '🕵🏿dark skin tone | detective | sleuth| spy', value: '🕵🏿' },
{ label: '💂guard', value: '💂' },
{ label: '💂🏻guard | light skin tone', value: '💂🏻' },
{ label: '💂🏼guard | medium-light skin tone', value: '💂🏼' },
{ label: '💂🏽guard | medium skin tone', value: '💂🏽' },
{ label: '💂🏾guard | medium-dark skin tone', value: '💂🏾' },
{ label: '💂🏿dark skin tone | guard', value: '💂🏿' },
{ label: '👷construction | hat| worker', value: '👷' },
{ label: '👷🏻construction | hat| light skin tone | worker', value: '👷🏻' },
{ label: '👷🏼construction | hat| medium-light skin tone | worker', value: '👷🏼' },
{ label: '👷🏽construction | hat| medium skin tone | worker', value: '👷🏽' },
{ label: '👷🏾construction | hat| medium-dark skin tone | worker', value: '👷🏾' },
{ label: '👷🏿construction | dark skin tone | hat | worker', value: '👷🏿' },
{ label: '👳turban', value: '👳' },
{ label: '👳🏻light skin tone | turban', value: '👳🏻' },
{ label: '👳🏼medium-light skin tone | turban', value: '👳🏼' },
{ label: '👳🏽medium skin tone | turban', value: '👳🏽' },
{ label: '👳🏾medium-dark skin tone | turban', value: '👳🏾' },
{ label: '👳🏿dark skin tone | turban', value: '👳🏿' },
{ label: '👱blond', value: '👱' },
{ label: '👱🏻blond | light skin tone', value: '👱🏻' },
{ label: '👱🏼blond | medium-light skin tone', value: '👱🏼' },
{ label: '👱🏽blond | medium skin tone', value: '👱🏽' },
{ label: '👱🏾blond | medium-dark skin tone', value: '👱🏾' },
{ label: '👱🏿blond | dark skin tone', value: '👱🏿' },
{ label: '🎅celebration | claus | father | santa', value: '🎅' },
{ label: '👸fairy tale | fantasy', value: '👸' },
{ label: '👸🏻fairy tale | fantasy | light skin tone', value: '👸🏻' },
{ label: '👸🏼fairy tale | fantasy | medium-light skin tone', value: '👸🏼' },
{ label: '👸🏽fairy tale | fantasy | medium skin tone', value: '👸🏽' },
{ label: '👸🏾fairy tale | fantasy | medium-dark skin tone', value: '👸🏾' },
{ label: '👸🏿dark skin tone | fairy tale | fantasy', value: '👸🏿' },
{ label: '👰bride | veil | wedding', value: '👰' },
{ label: '👰🏻bride | light skin tone | veil | wedding', value: '👰🏻' },
{ label: '👰🏼bride | medium-light skin tone | veil | wedding', value: '👰🏼' },
{ label: '👰🏽bride | medium skin tone | veil | wedding', value: '👰🏽' },
{ label: '👰🏾bride | medium-dark skin tone | veil | wedding', value: '👰🏾' },
{ label: '👰🏿bride | dark skin tone | veil | wedding', value: '👰🏿' },
{ label: '🤵groom | man | tuxedo', value: '🤵' },
{ label: '🤵🏻groom | light skin tone | man | tuxedo', value: '🤵🏻' },
{ label: '🤵🏼groom | man | medium-light skin tone | tuxedo', value: '🤵🏼' },
{ label: '🤵🏽groom | man | medium skin tone | tuxedo', value: '🤵🏽' },
{ label: '🤵🏾groom | man | medium-dark skin tone | tuxedo', value: '🤵🏾' },
{ label: '🤵🏿dark skin tone | groom | man | tuxedo', value: '🤵🏿' },
{ label: '🤰pregnant | woman', value: '🤰' },
{ label: '🤰🏻light skin tone | pregnant | woman', value: '🤰🏻' },
{ label: '🤰🏼medium-light skin tone | pregnant | woman', value: '🤰🏼' },
{ label: '🤰🏽medium skin tone | pregnant | woman', value: '🤰🏽' },
{ label: '🤰🏾medium-dark skin tone | pregnant | woman', value: '🤰🏾' },
{ label: '🤰🏿dark skin tone | pregnant | woman', value: '🤰🏿' },
{ label: '👲gua pi mao | hat| man', value: '👲' },
{ label: '👲🏻gua pi mao | hat| light skin tone | man', value: '👲🏻' },
{ label: '👲🏼gua pi mao | hat| man | medium-light skin tone', value: '👲🏼' },
{ label: '👲🏽gua pi mao | hat| man | medium skin tone', value: '👲🏽' },
{ label: '👲🏾gua pi mao | hat| man | medium-dark skin tone', value: '👲🏾' },
{ label: '👲🏿dark skin tone | gua pi mao | hat| man', value: '👲🏿' },
{ label: '🙍frown | gesture', value: '🙍' },
{ label: '🙍🏻frown | gesture | light skin tone', value: '🙍🏻' },
{ label: '🙍🏼frown | gesture | medium-light skin tone', value: '🙍🏼' },
{ label: '🙍🏽frown | gesture | medium skin tone', value: '🙍🏽' },
{ label: '🙍🏾frown | gesture | medium-dark skin tone', value: '🙍🏾' },
{ label: '🙍🏿dark skin tone | frown | gesture', value: '🙍🏿' },
{ label: '🙎gesture | pouting', value: '🙎' },
{ label: '🙎🏻gesture | light skin tone | pouting', value: '🙎🏻' },
{ label: '🙎🏼gesture | medium-light skin tone | pouting', value: '🙎🏼' },
{ label: '🙎🏽gesture | medium skin tone | pouting', value: '🙎🏽' },
{ label: '🙎🏾gesture | medium-dark skin tone | pouting', value: '🙎🏾' },
{ label: '🙎🏿dark skin tone | gesture | pouting', value: '🙎🏿' },
{ label: '🙅forbidden | gesture | hand | no | not | prohibited', value: '🙅' },
{ label: '🙅🏻forbidden | gesture | hand | light skin tone | no | not | prohibited', value: '🙅🏻' },
{ label: '🙅🏼forbidden | gesture | hand | medium-light skin tone | no | not | prohibited', value: '🙅🏼' },
{ label: '🙅🏽forbidden | gesture | hand | medium skin tone | no | not | prohibited', value: '🙅🏽' },
{ label: '🙅🏾forbidden | gesture | hand | medium-dark skin tone | no | not | prohibited', value: '🙅🏾' },
{ label: '🙅🏿dark skin tone | forbidden | gesture | hand | no | not | prohibited', value: '🙅🏿' },
{ label: '🙆gesture | hand | OK', value: '🙆' },
{ label: '🙆🏻gesture | hand | light skin tone | OK', value: '🙆🏻' },
{ label: '🙆🏼gesture | hand | medium-light skin tone | OK', value: '🙆🏼' },
{ label: '🙆🏽gesture | hand | medium skin tone | OK', value: '🙆🏽' },
{ label: '🙆🏾gesture | hand | medium-dark skin tone | OK', value: '🙆🏾' },
{ label: '🙆🏿dark skin tone | gesture | hand | OK', value: '🙆🏿' },
{ label: '💁hand | help | information | sassy | tipping', value: '💁' },
{ label: '💁🏻hand | help | information | light skin tone | sassy| tipping', value: '💁🏻' },
{ label: '💁🏼hand | help | information | medium-light skin tone | sassy| tipping', value: '💁🏼' },
{ label: '💁🏽hand | help | information | medium skin tone | sassy | tipping', value: '💁🏽' },
{ label: '💁🏾hand | help | information | medium-dark skin tone | sassy| tipping', value: '💁🏾' },
{ label: '💁🏿dark skin tone | hand | help | information | sassy | tipping', value: '💁🏿' },
{ label: '🙋gesture | hand | happy | raised', value: '🙋' },
{ label: '🙋🏻gesture | hand | happy | light skin tone | raised', value: '🙋🏻' },
{ label: '🙋🏼gesture | hand | happy | medium-light skin tone | raised', value: '🙋🏼' },
{ label: '🙋🏽gesture | hand | happy | medium skin tone | raised', value: '🙋🏽' },
{ label: '🙋🏾gesture | hand | happy | medium-dark skin tone | raised', value: '🙋🏾' },
{ label: '🙋🏿dark skin tone | gesture | hand | happy | raised', value: '🙋🏿' },
{ label: '🙇apology | bow | gesture | sorry', value: '🙇' },
{ label: '🙇🏻apology | bow | gesture | light skin tone | sorry', value: '🙇🏻' },
{ label: '🙇🏼apology | bow | gesture | medium-light skin tone | sorry', value: '🙇🏼' },
{ label: '🙇🏽apology | bow | gesture | medium skin tone | sorry', value: '🙇🏽' },
{ label: '🙇🏾apology | bow | gesture | medium-dark skin tone | sorry', value: '🙇🏾' },
{ label: '🙇🏿apology | bow | dark skin tone | gesture | sorry', value: '🙇🏿' },
{ label: '💆face | massage | salon', value: '💆' },
{ label: '💆🏻face | light skin tone | massage | salon', value: '💆🏻' },
{ label: '💆🏼face | massage | medium-light skin tone | salon', value: '💆🏼' },
{ label: '💆🏽face | massage | medium skin tone | salon', value: '💆🏽' },
{ label: '💆🏾face | massage | medium-dark skin tone | salon', value: '💆🏾' },
{ label: '💆🏿dark skin tone | face | massage | salon', value: '💆🏿' },
{ label: '💇barber | beauty | haircut | parlor', value: '💇' },
{ label: '💇🏻barber | beauty | haircut | light skin tone | parlor', value: '💇🏻' },
{ label: '💇🏼barber | beauty | haircut | medium-light skin tone | parlor', value: '💇🏼' },
{ label: '💇🏽barber | beauty | haircut | medium skin tone | parlor', value: '💇🏽' },
{ label: '💇🏾barber | beauty | haircut | medium-dark skin tone | parlor', value: '💇🏾' },
{ label: '💇🏿barber | beauty | dark skin tone | haircut | parlor', value: '💇🏿' },
{ label: '🚶hike | walk | walking', value: '🚶' },
{ label: '🚶🏻hike | light skin tone | walk | walking', value: '🚶🏻' },
{ label: '🚶🏼hike | medium-light skin tone | walk | walking', value: '🚶🏼' },
{ label: '🚶🏽hike | medium skin tone | walk | walking', value: '🚶🏽' },
{ label: '🚶🏾hike | medium-dark skin tone | walk | walking', value: '🚶🏾' },
{ label: '🚶🏿dark skin tone | hike | walk | walking', value: '🚶🏿' },
{ label: '🏃marathon | running', value: '🏃' },
{ label: '🏃🏻light skin tone | marathon | running', value: '🏃🏻' },
{ label: '🏃🏼marathon | medium-light skin tone | running', value: '🏃🏼' },
{ label: '🏃🏽marathon | medium skin tone | running', value: '🏃🏽' },
{ label: '🏃🏾marathon | medium-dark skin tone | running', value: '🏃🏾' },
{ label: '🏃🏿dark skin tone | marathon | running', value: '🏃🏿' },
{ label: '💃dancing | woman', value: '💃' },
{ label: '💃🏻dancing | light skin tone | woman', value: '💃🏻' },
{ label: '💃🏼dancing | medium-light skin tone | woman', value: '💃🏼' },
{ label: '💃🏽dancing | medium skin tone | woman', value: '💃🏽' },
{ label: '💃🏾dancing | medium-dark skin tone | woman', value: '💃🏾' },
{ label: '💃🏿dancing | dark skin tone | woman', value: '💃🏿' },
{ label: '🕺dance | man', value: '🕺' },
{ label: '🕺🏻dance | light skin tone | man', value: '🕺🏻' },
{ label: '🕺🏼dance | man | medium-light skin tone', value: '🕺🏼' },
{ label: '🕺🏽dance | man | medium skin tone', value: '🕺🏽' },
{ label: '🕺🏾dance | man | medium-dark skin tone', value: '🕺🏾' },
{ label: '🕺🏿dance | dark skin tone | man', value: '🕺🏿' },
{ label: '👯bunny ear | dancer | partying', value: '👯' },
{ label: '🕴business | man | suit', value: '🕴' },
{ label: '🗣face | head | silhouette | speak | speaking', value: '🗣' },
{ label: '👤bust | silhouette', value: '👤' },
{ label: '👥bust | silhouette', value: '👥' },
{ label: '🤺fencer | fencing | sword', value: '🤺' },
{ label: '🏇horse | jockey | racehorse | racing', value: '🏇' },
{ label: '🏇🏻horse | jockey | light skin tone | racehorse | racing', value: '🏇🏻' },
{ label: '🏇🏼horse | jockey | medium-light skin tone | racehorse | racing', value: '🏇🏼' },
{ label: '🏇🏽horse | jockey | medium skin tone | racehorse| racing', value: '🏇🏽' },
{ label: '🏇🏾horse | jockey | medium-dark skin tone | racehorse | racing', value: '🏇🏾' },
{ label: '🏇🏿dark skin tone | horse | jockey | racehorse | racing', value: '🏇🏿' },
{ label: '⛷ski | snow', value: '⛷' },
{ label: '🏂ski | snow | snowboard', value: '🏂' },
{ label: '🏌ball | golf', value: '🏌' },
{ label: '🏄surfing', value: '🏄' },
{ label: '🏄🏻light skin tone | surfing', value: '🏄🏻' },
{ label: '🏄🏼medium-light skin tone | surfing', value: '🏄🏼' },
{ label: '🏄🏽medium skin tone | surfing', value: '🏄🏽' },
{ label: '🏄🏾medium-dark skin tone | surfing', value: '🏄🏾' },
{ label: '🏄🏿dark skin tone | surfing', value: '🏄🏿' },
{ label: '🚣boat | rowboat', value: '🚣' },
{ label: '🚣🏻boat | light skin tone | rowboat', value: '🚣🏻' },
{ label: '🚣🏼boat | medium-light skin tone | rowboat', value: '🚣🏼' },
{ label: '🚣🏽boat | medium skin tone | rowboat', value: '🚣🏽' },
{ label: '🚣🏾boat | medium-dark skin tone | rowboat', value: '🚣🏾' },
{ label: '🚣🏿boat | dark skin tone | rowboat', value: '🚣🏿' },
{ label: '🏊swim', value: '🏊' },
{ label: '🏊🏻light skin tone | swim', value: '🏊🏻' },
{ label: '🏊🏼medium-light skin tone | swim', value: '🏊🏼' },
{ label: '🏊🏽medium skin tone | swim', value: '🏊🏽' },
{ label: '🏊🏾medium-dark skin tone | swim', value: '🏊🏾' },
{ label: '🏊🏿dark skin tone | swim', value: '🏊🏿' },
{ label: '⛹ball', value: '⛹' },
{ label: '⛹🏻ball | light skin tone', value: '⛹🏻' },
{ label: '⛹🏼ball | medium-light skin tone', value: '⛹🏼' },
{ label: '⛹🏽ball | medium skin tone', value: '⛹🏽' },
{ label: '⛹🏾ball | medium-dark skin tone', value: '⛹🏾' },
{ label: '⛹🏿ball | dark skin tone', value: '⛹🏿' },
{ label: '🏋lifter | weight', value: '🏋' },
{ label: '🏋🏻lifter | light skin tone | weight', value: '🏋🏻' },
{ label: '🏋🏼lifter | medium-light skin tone | weight', value: '🏋🏼' },
{ label: '🏋🏽lifter | medium skin tone | weight', value: '🏋🏽' },
{ label: '🏋🏾lifter | medium-dark skin tone | weight', value: '🏋🏾' },
{ label: '🏋🏿dark skin tone | lifter | weight', value: '🏋🏿' },
{ label: '🚴bicycle | biking | cyclist', value: '🚴' },
{ label: '🚴🏻bicycle | biking | cyclist | light skin tone', value: '🚴🏻' },
{ label: '🚴🏼bicycle | biking | cyclist | medium-light skin tone', value: '🚴🏼' },
{ label: '🚴🏽bicycle | biking | cyclist | medium skin tone', value: '🚴🏽' },
{ label: '🚴🏾bicycle | biking | cyclist | medium-dark skin tone', value: '🚴🏾' },
{ label: '🚴🏿bicycle | biking | cyclist | dark skin tone', value: '🚴🏿' },
{ label: '🚵bicycle | bicyclist| bike | cyclist | mountain', value: '🚵' },
{ label: '🚵🏻bicycle | bicyclist| bike | cyclist | light skin tone | mountain', value: '🚵🏻' },
{ label: '🚵🏼bicycle | bicyclist| bike | cyclist | medium-light skin tone | mountain', value: '🚵🏼' },
{ label: '🚵🏽bicycle | bicyclist| bike | cyclist | medium skin tone | mountain', value: '🚵🏽' },
{ label: '🚵🏾bicycle | bicyclist| bike | cyclist | medium-dark skin tone | mountain', value: '🚵🏾' },
{ label: '🚵🏿bicycle | bicyclist| bike | cyclist | dark skin tone | mountain', value: '🚵🏿' },
{ label: '🏎car | racing', value: '🏎' },
{ label: '🏍racing', value: '🏍' },
{ label: '👫couple | hand | hold | man | woman', value: '👫' },
{ label: '👬couple | Gemini | hand | hold | man | twins | zodiac', value: '👬' },
{ label: '👭couple | hand | hold | woman', value: '👭' },
{ label: '💏couple', value: '💏' },
{ label: '👨‍❤️‍💋‍👨couple | man', value: '👨‍❤️‍💋‍👨' },
{ label: '👩‍❤️‍💋‍👩couple | woman', value: '👩‍❤️‍💋‍👩' },
{ label: '💑couple | love', value: '💑' },
{ label: '👨‍❤️‍👨couple | love | man', value: '👨‍❤️‍👨' },
{ label: '👩‍❤️‍👩couple | love | woman', value: '👩‍❤️‍👩' },
{ label: '👪family', value: '👪' },
{ label: '👨‍👩‍👧family | girl | man| woman', value: '👨‍👩‍👧' },
{ label: '👨‍👩‍👧‍👦boy | family | girl| man | woman', value: '👨‍👩‍👧‍👦' },
{ label: '👨‍👩‍👦‍👦boy | family | man | woman', value: '👨‍👩‍👦‍👦' },
{ label: '👨‍👩‍👧‍👧family | girl | man| woman', value: '👨‍👩‍👧‍👧' },
{ label: '👨‍👨‍👦boy | family | man', value: '👨‍👨‍👦' },
{ label: '👨‍👨‍👧family | girl | man', value: '👨‍👨‍👧' },
{ label: '👨‍👨‍👧‍👦boy | family | girl| man', value: '👨‍👨‍👧‍👦' },
{ label: '👨‍👨‍👦‍👦boy | family | man', value: '👨‍👨‍👦‍👦' },
{ label: '👨‍👨‍👧‍👧family | girl | man', value: '👨‍👨‍👧‍👧' },
{ label: '👩‍👩‍👦boy | family | woman', value: '👩‍👩‍👦' },
{ label: '👩‍👩‍👧family | girl | woman', value: '👩‍👩‍👧' },
{ label: '👩‍👩‍👧‍👦boy | family | girl| woman', value: '👩‍👩‍👧‍👦' },
{ label: '👩‍👩‍👦‍👦boy | family | woman', value: '👩‍👩‍👦‍👦' },
{ label: '👩‍👩‍👧‍👧family | girl | woman', value: '👩‍👩‍👧‍👧' },
{ label: '🏻skin tone | type 1–2', value: '🏻' },
{ label: '🏼skin tone | type 3', value: '🏼' },
{ label: '🏽skin tone | type 4', value: '🏽' },
{ label: '🏾skin tone | type 5', value: '🏾' },
{ label: '🏿skin tone | type 6', value: '🏿' },
{ label: '💪biceps | comic | flex | muscle', value: '💪' },
{ label: '💪🏻biceps | comic | flex | light skin tone | muscle', value: '💪🏻' },
{ label: '💪🏼biceps | comic | flex | medium-light skin tone | muscle', value: '💪🏼' },
{ label: '💪🏽biceps | comic | flex | medium skin tone | muscle', value: '💪🏽' },
{ label: '💪🏾biceps | comic | flex | medium-dark skin tone | muscle', value: '💪🏾' },
{ label: '💪🏿biceps | comic | dark skin tone | flex | muscle', value: '💪🏿' },
{ label: '👈backhand | finger | hand | index | point', value: '👈' },
{ label: '👈🏻backhand | finger | hand | index | light skin tone | point', value: '👈🏻' },
{ label: '👈🏼backhand | finger | hand | index | medium-light skin tone | point', value: '👈🏼' },
{ label: '👈🏽backhand | finger | hand | index | medium skin tone | point', value: '👈🏽' },
{ label: '👈🏾backhand | finger | hand | index | medium-dark skin tone | point', value: '👈🏾' },
{ label: '👈🏿backhand | dark skin tone | finger| hand | index | point', value: '👈🏿' },
{ label: '👉backhand | finger | hand | index | point', value: '👉' },
{ label: '👉🏻backhand | finger | hand | index | light skin tone | point', value: '👉🏻' },
{ label: '👉🏼backhand | finger | hand | index | medium-light skin tone | point', value: '👉🏼' },
{ label: '👉🏽backhand | finger | hand | index | medium skin tone | point', value: '👉🏽' },
{ label: '👉🏾backhand | finger | hand | index | medium-dark skin tone | point', value: '👉🏾' },
{ label: '👉🏿backhand | dark skin tone | finger| hand | index | point', value: '👉🏿' },
{ label: '☝finger | hand | index | point | up', value: '☝' },
{ label: '☝🏻finger | hand | index | light skin tone | point | up', value: '☝🏻' },
{ label: '☝🏼finger | hand | index | medium-light skin tone | point | up', value: '☝🏼' },
{ label: '☝🏽finger | hand | index | medium skin tone | point | up', value: '☝🏽' },
{ label: '☝🏾finger | hand | index | medium-dark skin tone | point | up', value: '☝🏾' },
{ label: '☝🏿dark skin tone | finger | hand | index | point | up', value: '☝🏿' },
{ label: '👆backhand | finger | hand | index | point | up', value: '👆' },
{ label: '👆🏻backhand | finger | hand | index | light skin tone | point | up', value: '👆🏻' },
{ label: '👆🏼backhand | finger | hand | index | medium-light skin tone | point | up', value: '👆🏼' },
{ label: '👆🏽backhand | finger | hand | index | medium skin tone | point | up', value: '👆🏽' },
{ label: '👆🏾backhand | finger | hand | index | medium-dark skin tone | point | up', value: '👆🏾' },
{ label: '👆🏿backhand | dark skin tone | finger| hand | index | point | up', value: '👆🏿' },
{ label: '🖕finger | hand', value: '🖕' },
{ label: '🖕🏻finger | hand | light skin tone', value: '🖕🏻' },
{ label: '🖕🏼finger | hand | medium-light skin tone', value: '🖕🏼' },
{ label: '🖕🏽finger | hand | medium skin tone', value: '🖕🏽' },
{ label: '🖕🏾finger | hand | medium-dark skin tone', value: '🖕🏾' },
{ label: '🖕🏿dark skin tone | finger | hand', value: '🖕🏿' },
{ label: '👇backhand | down| finger | hand | index | point', value: '👇' },
{ label: '👇🏻backhand | down| finger | hand | index | light skin tone | point', value: '👇🏻' },
{ label: '👇🏼backhand | down| finger | hand | index | medium-light skin tone | point', value: '👇🏼' },
{ label: '👇🏽backhand | down| finger | hand | index | medium skin tone | point', value: '👇🏽' },
{ label: '👇🏾backhand | down| finger | hand | index | medium-dark skin tone | point', value: '👇🏾' },
{ label: '👇🏿backhand | dark skin tone | down| finger | hand | index | point', value: '👇🏿' },
{ label: '✌hand | v | victory', value: '✌' },
{ label: '✌🏻hand | light skin tone | v | victory', value: '✌🏻' },
{ label: '✌🏼hand | medium-light skin tone | v| victory', value: '✌🏼' },
{ label: '✌🏽hand | medium skin tone | v | victory', value: '✌🏽' },
{ label: '✌🏾hand | medium-dark skin tone | v| victory', value: '✌🏾' },
{ label: '✌🏿dark skin tone | hand | v | victory', value: '✌🏿' },
{ label: '🤞cross | finger | hand | luck', value: '🤞' },
{ label: '🤞🏻cross | finger | hand | light skin tone | luck', value: '🤞🏻' },
{ label: '🤞🏼cross | finger | hand | luck | medium-light skin tone', value: '🤞🏼' },
{ label: '🤞🏽cross | finger | hand | luck | medium skin tone', value: '🤞🏽' },
{ label: '🤞🏾cross | finger | hand | luck | medium-dark skin tone', value: '🤞🏾' },
{ label: '🤞🏿cross | dark skin tone | finger | hand | luck', value: '🤞🏿' },
{ label: '🖖finger | hand | spock | vulcan', value: '🖖' },
{ label: '🖖🏻finger | hand | light skin tone | spock | vulcan', value: '🖖🏻' },
{ label: '🖖🏼finger | hand | medium-light skin tone | spock| vulcan', value: '🖖🏼' },
{ label: '🖖🏽finger | hand | medium skin tone | spock | vulcan', value: '🖖🏽' },
{ label: '🖖🏾finger | hand | medium-dark skin tone | spock| vulcan', value: '🖖🏾' },
{ label: '🖖🏿dark skin tone | finger | hand | spock | vulcan', value: '🖖🏿' },
{ label: '🤘finger | hand | horns | rock-on', value: '🤘' },
{ label: '🤘🏻finger | hand | horns | light skin tone | rock-on', value: '🤘🏻' },
{ label: '🤘🏼finger | hand | horns | medium-light skin tone | rock-on', value: '🤘🏼' },
{ label: '🤘🏽finger | hand | horns | medium skin tone | rock-on', value: '🤘🏽' },
{ label: '🤘🏾finger | hand | horns | medium-dark skin tone | rock-on', value: '🤘🏾' },
{ label: '🤘🏿dark skin tone | finger | hand | horns | rock-on', value: '🤘🏿' },
{ label: '🤙call | hand', value: '🤙' },
{ label: '🤙🏻call | hand | light skin tone', value: '🤙🏻' },
{ label: '🤙🏼call | hand | medium-light skin tone', value: '🤙🏼' },
{ label: '🤙🏽call | hand | medium skin tone', value: '🤙🏽' },
{ label: '🤙🏾call | hand | medium-dark skin tone', value: '🤙🏾' },
{ label: '🤙🏿call | dark skin tone | hand', value: '🤙🏿' },
{ label: '🖐finger | hand | splayed', value: '🖐' },
{ label: '🖐🏻finger | hand | light skin tone | splayed', value: '🖐🏻' },
{ label: '🖐🏼finger | hand | medium-light skin tone | splayed', value: '🖐🏼' },
{ label: '🖐🏽finger | hand | medium skin tone | splayed', value: '🖐🏽' },
{ label: '🖐🏾finger | hand | medium-dark skin tone | splayed', value: '🖐🏾' },
{ label: '🖐🏿dark skin tone | finger | hand | splayed', value: '🖐🏿' },
{ label: '✋hand', value: '✋' },
{ label: '✋🏻hand | light skin tone', value: '✋🏻' },
{ label: '✋🏼hand | medium-light skin tone', value: '✋🏼' },
{ label: '✋🏽hand | medium skin tone', value: '✋🏽' },
{ label: '✋🏾hand | medium-dark skin tone', value: '✋🏾' },
{ label: '✋🏿dark skin tone | hand', value: '✋🏿' },
{ label: '👌hand | OK', value: '👌' },
{ label: '👌🏻hand | light skin tone | OK', value: '👌🏻' },
{ label: '👌🏼hand | medium-light skin tone | OK', value: '👌🏼' },
{ label: '👌🏽hand | medium skin tone | OK', value: '👌🏽' },
{ label: '👌🏾hand | medium-dark skin tone | OK', value: '👌🏾' },
{ label: '👌🏿dark skin tone | hand | OK', value: '👌🏿' },
{ label: '👍+1 | hand | thumb | up', value: '👍' },
{ label: '👍🏻+1 | hand | light skin tone | thumb| up', value: '👍🏻' },
{ label: '👍🏼+1 | hand | medium-light skin tone | thumb| up', value: '👍🏼' },
{ label: '👍🏽+1 | hand | medium skin tone | thumb | up', value: '👍🏽' },
{ label: '👍🏾+1 | hand | medium-dark skin tone | thumb| up', value: '👍🏾' },
{ label: '👍🏿+1 | dark skin tone | hand | thumb | up', value: '👍🏿' },
{ label: '👎-1 | down | hand| thumb', value: '👎' },
{ label: '👎🏻-1 | down | hand| light skin tone | thumb', value: '👎🏻' },
{ label: '👎🏼-1 | down | hand| medium-light skin tone | thumb', value: '👎🏼' },
{ label: '👎🏽-1 | down | hand| medium skin tone | thumb', value: '👎🏽' },
{ label: '👎🏾-1 | down | hand| medium-dark skin tone | thumb', value: '👎🏾' },
{ label: '👎🏿-1 | dark skin tone | down | hand | thumb', value: '👎🏿' },
{ label: '✊clenched | fist | hand | punch', value: '✊' },
{ label: '✊🏻clenched | fist | hand | light skin tone | punch', value: '✊🏻' },
{ label: '✊🏼clenched | fist | hand | medium-light skin tone | punch', value: '✊🏼' },
{ label: '✊🏽clenched | fist | hand | medium skin tone | punch', value: '✊🏽' },
{ label: '✊🏾clenched | fist | hand | medium-dark skin tone | punch', value: '✊🏾' },
{ label: '✊🏿clenched | dark skin tone | fist | hand | punch', value: '✊🏿' },
{ label: '👊clenched | fist | hand | punch', value: '👊' },
{ label: '👊🏻clenched | fist | hand | light skin tone | punch', value: '👊🏻' },
{ label: '👊🏼clenched | fist | hand | medium-light skin tone | punch', value: '👊🏼' },
{ label: '👊🏽clenched | fist | hand | medium skin tone | punch', value: '👊🏽' },
{ label: '👊🏾clenched | fist | hand | medium-dark skin tone | punch', value: '👊🏾' },
{ label: '👊🏿clenched | dark skin tone | fist | hand | punch', value: '👊🏿' },
{ label: '👋hand | wave | waving', value: '👋' },
{ label: '👋🏻hand | light skin tone | wave | waving', value: '👋🏻' },
{ label: '👋🏼hand | medium-light skin tone | wave | waving', value: '👋🏼' },
{ label: '👋🏽hand | medium skin tone | wave| waving', value: '👋🏽' },
{ label: '👋🏾hand | medium-dark skin tone | wave | waving', value: '👋🏾' },
{ label: '👋🏿dark skin tone | hand | wave | waving', value: '👋🏿' },
{ label: '👏clap | hand', value: '👏' },
{ label: '👏🏻clap | hand | light skin tone', value: '👏🏻' },
{ label: '👏🏼clap | hand | medium-light skin tone', value: '👏🏼' },
{ label: '👏🏽clap | hand | medium skin tone', value: '👏🏽' },
{ label: '👏🏾clap | hand | medium-dark skin tone', value: '👏🏾' },
{ label: '👏🏿clap | dark skin tone | hand', value: '👏🏿' },
{ label: '✍hand | write', value: '✍' },
{ label: '✍🏻hand | light skin tone | write', value: '✍🏻' },
{ label: '✍🏼hand | medium-light skin tone | write', value: '✍🏼' },
{ label: '✍🏽hand | medium skin tone | write', value: '✍🏽' },
{ label: '✍🏾hand | medium-dark skin tone | write', value: '✍🏾' },
{ label: '✍🏿dark skin tone | hand | write', value: '✍🏿' },
{ label: '👐hand', value: '👐' },
{ label: '👐🏻hand | light skin tone', value: '👐🏻' },
{ label: '👐🏼hand | medium-light skin tone', value: '👐🏼' },
{ label: '👐🏽hand | medium skin tone', value: '👐🏽' },
{ label: '👐🏾hand | medium-dark skin tone', value: '👐🏾' },
{ label: '👐🏿dark skin tone | hand', value: '👐🏿' },
{ label: '🙌celebration | gesture | hand | hooray | raised', value: '🙌' },
{ label: '🙌🏻celebration | gesture | hand | hooray | light skin tone | raised', value: '🙌🏻' },
{ label: '🙌🏼celebration | gesture | hand | hooray | medium-light skin tone | raised', value: '🙌🏼' },
{ label: '🙌🏽celebration | gesture | hand | hooray | medium skin tone | raised', value: '🙌🏽' },
{ label: '🙌🏾celebration | gesture | hand | hooray | medium-dark skin tone | raised', value: '🙌🏾' },
{ label: '🙌🏿celebration | dark skin tone | gesture | hand | hooray | raised', value: '🙌🏿' },
{ label: '🙏ask | bow | folded | gesture | hand | please | pray | thanks', value: '🙏' },
{ label: '🙏🏻ask | bow | folded | gesture | hand | light skin tone | please | pray | thanks', value: '🙏🏻' },
{ label: '🙏🏼ask | bow | folded | gesture | hand | medium-light skin tone | please | pray | thanks', value: '🙏🏼' },
{ label: '🙏🏽ask | bow | folded | gesture | hand | medium skin tone | please | pray | thanks', value: '🙏🏽' },
{ label: '🙏🏾ask | bow | folded | gesture | hand | medium-dark skin tone | please | pray | thanks', value: '🙏🏾' },
{ label: '🙏🏿ask | bow | dark skin tone | folded| gesture | hand | please | pray | thanks', value: '🙏🏿' },
{ label: '🤝agreement | hand | handshake | meeting | shake', value: '🤝' },
{ label: '🤝🏻agreement | hand | handshake | light skin tone | meeting | shake', value: '🤝🏻' },
{ label: '🤝🏼agreement | hand | handshake | medium-light skin tone | meeting | shake', value: '🤝🏼' },
{ label: '🤝🏽agreement | hand | handshake | medium skin tone | meeting | shake', value: '🤝🏽' },
{ label: '🤝🏾agreement | hand | handshake | medium-dark skin tone | meeting | shake', value: '🤝🏾' },
{ label: '🤝🏿agreement | dark skin tone | hand | handshake | meeting | shake', value: '🤝🏿' },
{ label: '💅care | cosmetics| manicure | nail | polish', value: '💅' },
{ label: '💅🏻care | cosmetics| light skin tone | manicure | nail | polish', value: '💅🏻' },
{ label: '💅🏼care | cosmetics| manicure | medium-light skin tone | nail | polish', value: '💅🏼' },
{ label: '💅🏽care | cosmetics| manicure | medium skin tone | nail | polish', value: '💅🏽' },
{ label: '💅🏾care | cosmetics| manicure | medium-dark skin tone | nail | polish', value: '💅🏾' },
{ label: '💅🏿care | cosmetics| dark skin tone | manicure | nail | polish', value: '💅🏿' },
{ label: '👂body', value: '👂' },
{ label: '👂🏻body | light skin tone', value: '👂🏻' },
{ label: '👂🏼body | medium-light skin tone', value: '👂🏼' },
{ label: '👂🏽body | medium skin tone', value: '👂🏽' },
{ label: '👂🏾body | medium-dark skin tone', value: '👂🏾' },
{ label: '👂🏿body | dark skin tone', value: '👂🏿' },
{ label: '👃body', value: '👃' },
{ label: '👃🏻body | light skin tone', value: '👃🏻' },
{ label: '👃🏼body | medium-light skin tone', value: '👃🏼' },
{ label: '👃🏽body | medium skin tone', value: '👃🏽' },
{ label: '👃🏾body | medium-dark skin tone', value: '👃🏾' },
{ label: '👃🏿body | dark skin tone', value: '👃🏿' },
{ label: '👣clothing | footprint | print', value: '👣' },
{ label: '👀eye | face', value: '👀' },
{ label: '👁body', value: '👁' },
{ label: '👅body', value: '👅' },
{ label: '👄lips', value: '👄' },
{ label: '💋kiss | lips', value: '💋' },
{ label: '💘arrow | cupid', value: '💘' },
{ label: '❤heart', value: '❤' },
{ label: '💓beating | heartbeat | pulsating', value: '💓' },
{ label: '💔break | broken', value: '💔' },
{ label: '💕love', value: '💕' },
{ label: '💖excited | sparkle', value: '💖' },
{ label: '💗excited | growing| nervous | pulse', value: '💗' },
{ label: '💙blue', value: '💙' },
{ label: '💚green', value: '💚' },
{ label: '💛yellow', value: '💛' },
{ label: '💜purple', value: '💜' },
{ label: '🖤black | evil | wicked', value: '🖤' },
{ label: '💝ribbon | valentine', value: '💝' },
{ label: '💞revolving', value: '💞' },
{ label: '💟heart', value: '💟' },
{ label: '❣exclamation | mark | punctuation', value: '❣' },
{ label: '💌heart | letter | love | mail', value: '💌' },
{ label: '💤comic | sleep', value: '💤' },
{ label: '💢angry | comic | mad', value: '💢' },
{ label: '💣comic', value: '💣' },
{ label: '💥boom | comic', value: '💥' },
{ label: '💦comic | splashing | sweat', value: '💦' },
{ label: '💨comic | dash | running', value: '💨' },
{ label: '💫comic | star', value: '💫' },
{ label: '💬balloon | bubble | comic | dialog | speech', value: '💬' },
{ label: '🗯angry | balloon | bubble | mad', value: '🗯' },
{ label: '💭balloon | bubble | comic | thought', value: '💭' },
{ label: '🕳hole', value: '🕳' },
{ label: '👓clothing | eye | eyeglasses | eyewear', value: '👓' },
{ label: '🕶dark | eye | eyewear | glasses', value: '🕶' },
{ label: '👔clothing', value: '👔' },
{ label: '👕clothing | shirt | tshirt', value: '👕' },
{ label: '👖clothing | pants | trousers', value: '👖' },
{ label: '👗clothing', value: '👗' },
{ label: '👘clothing', value: '👘' },
{ label: '👙clothing | swim', value: '👙' },
{ label: '👚clothing | woman', value: '👚' },
{ label: '👛clothing | coin', value: '👛' },
{ label: '👜bag | clothing | purse', value: '👜' },
{ label: '👝bag | clothing | pouch', value: '👝' },
{ label: '🛍bag | hotel | shopping', value: '🛍' },
{ label: '🎒bag | satchel | school', value: '🎒' },
{ label: '👞clothing | man | shoe', value: '👞' },
{ label: '👟athletic | clothing| shoe | sneaker', value: '👟' },
{ label: '👠clothing | heel | shoe | woman', value: '👠' },
{ label: '👡clothing | sandal| shoe | woman', value: '👡' },
{ label: '👢boot | clothing | shoe | woman', value: '👢' },
{ label: '👑clothing | king | queen', value: '👑' },
{ label: '👒clothing | hat | woman', value: '👒' },
{ label: '🎩clothing | hat | top | tophat', value: '🎩' },
{ label: '🎓cap | celebration| clothing | graduation | hat', value: '🎓' },
{ label: '⛑aid | cross | face| hat | helmet', value: '⛑' },
{ label: '📿beads | clothing | necklace | prayer| religion', value: '📿' },
{ label: '💄cosmetics | makeup', value: '💄' },
{ label: '💍diamond', value: '💍' },
{ label: '💎diamond | gem | jewel', value: '💎' },
{ label: '🐵face | monkey', value: '🐵' },
{ label: '🐒monkey', value: '🐒' },
{ label: '🐶dog | face | pet', value: '🐶' },
{ label: '🐕pet', value: '🐕' },
{ label: '🐩dog', value: '🐩' },
{ label: '🐺face | wolf', value: '🐺' },
{ label: '🐱cat | face | pet', value: '🐱' },
{ label: '🐈pet', value: '🐈' },
{ label: '🦁face | Leo | lion | zodiac', value: '🦁' },
{ label: '🐯face | tiger', value: '🐯' },
{ label: '🐅tiger', value: '🐅' },
{ label: '🐆leopard', value: '🐆' },
{ label: '🐴face | horse', value: '🐴' },
{ label: '🐎equestrian | racehorse | racing', value: '🐎' },
{ label: '🦄face | unicorn', value: '🦄' },
{ label: '🐮cow | face', value: '🐮' },
{ label: '🐂bull | Taurus | zodiac', value: '🐂' },
{ label: '🐃buffalo | water', value: '🐃' },
{ label: '🐄cow', value: '🐄' },
{ label: '🐷face | pig', value: '🐷' },
{ label: '🐖sow', value: '🐖' },
{ label: '🐗pig', value: '🐗' },
{ label: '🐽face | nose | pig', value: '🐽' },
{ label: '🐏Aries | sheep | zodiac', value: '🐏' },
{ label: '🐑ewe', value: '🐑' },
{ label: '🐐Capricorn | zodiac', value: '🐐' },
{ label: '🐪dromedary | hump', value: '🐪' },
{ label: '🐫bactrian | camel | hump', value: '🐫' },
{ label: '🐘elephant', value: '🐘' },
{ label: '🐭face | mouse', value: '🐭' },
{ label: '🐁mouse', value: '🐁' },
{ label: '🐀rat', value: '🐀' },
{ label: '🐹face | hamster | pet', value: '🐹' },
{ label: '🐰bunny | face | pet | rabbit', value: '🐰' },
{ label: '🐇bunny | pet', value: '🐇' },
{ label: '🐿chipmunk', value: '🐿' },
{ label: '🐻bear | face', value: '🐻' },
{ label: '🐨bear', value: '🐨' },
{ label: '🐼face | panda', value: '🐼' },
{ label: '🐾feet | paw | print', value: '🐾' },
{ label: '🦃turkey', value: '🦃' },
{ label: '🐔chicken', value: '🐔' },
{ label: '🐓rooster', value: '🐓' },
{ label: '🐣baby | chick | hatching', value: '🐣' },
{ label: '🐤baby | chick', value: '🐤' },
{ label: '🐥baby | chick', value: '🐥' },
{ label: '🐦bird', value: '🐦' },
{ label: '🐧penguin', value: '🐧' },
{ label: '🕊bird | fly | peace', value: '🕊' },
{ label: '🐸face | frog', value: '🐸' },
{ label: '🐊crocodile', value: '🐊' },
{ label: '🐢terrapin | tortoise| turtle', value: '🐢' },
{ label: '🐍bearer | Ophiuchus | serpent | zodiac', value: '🐍' },
{ label: '🐲dragon | face | fairy tale', value: '🐲' },
{ label: '🐉fairy tale', value: '🐉' },
{ label: '🐳face | spouting | whale', value: '🐳' },
{ label: '🐋whale', value: '🐋' },
{ label: '🐬flipper', value: '🐬' },
{ label: '🐟Pisces | zodiac', value: '🐟' },
{ label: '🐠fish | tropical', value: '🐠' },
{ label: '🐡fish', value: '🐡' },
{ label: '🐙octopus', value: '🐙' },
{ label: '🐚shell | spiral', value: '🐚' },
{ label: '🦀Cancer | zodiac', value: '🦀' },
{ label: '🐌snail', value: '🐌' },
{ label: '🐛insect', value: '🐛' },
{ label: '🐜insect', value: '🐜' },
{ label: '🐝bee | insect', value: '🐝' },
{ label: '🐞beetle | insect | ladybird | ladybug', value: '🐞' },
{ label: '🕷insect', value: '🕷' },
{ label: '🕸spider | web', value: '🕸' },
{ label: '🦂scorpio | Scorpius | zodiac', value: '🦂' },
{ label: '💐flower', value: '💐' },
{ label: '🌸blossom | cherry| flower', value: '🌸' },
{ label: '💮flower', value: '💮' },
{ label: '🏵plant', value: '🏵' },
{ label: '🌹flower', value: '🌹' },
{ label: '🥀flower | wilted', value: '🥀' },
{ label: '🌺flower', value: '🌺' },
{ label: '🌻flower | sun', value: '🌻' },
{ label: '🌼flower', value: '🌼' },
{ label: '🌷flower', value: '🌷' },
{ label: '🌱young', value: '🌱' },
{ label: '🌲tree', value: '🌲' },
{ label: '🌳deciduous | shedding | tree', value: '🌳' },
{ label: '🌴palm | tree', value: '🌴' },
{ label: '🌵plant', value: '🌵' },
{ label: '🌾ear | grain | rice', value: '🌾' },
{ label: '🌿leaf', value: '🌿' },
{ label: '☘plant', value: '☘' },
{ label: '🍀4 | clover | four | leaf', value: '🍀' },
{ label: '🍁falling | leaf | maple', value: '🍁' },
{ label: '🍂falling | leaf', value: '🍂' },
{ label: '🍃blow | flutter | leaf | wind', value: '🍃' },
{ label: '🍇fruit | grape', value: '🍇' },
{ label: '🍈fruit', value: '🍈' },
{ label: '🍉fruit', value: '🍉' },
{ label: '🍊fruit | orange', value: '🍊' },
{ label: '🍋citrus | fruit', value: '🍋' },
{ label: '🍌fruit', value: '🍌' },
{ label: '🍍fruit', value: '🍍' },
{ label: '🍎apple | fruit | red', value: '🍎' },
{ label: '🍏apple | fruit | green', value: '🍏' },
{ label: '🍐fruit', value: '🍐' },
{ label: '🍑fruit', value: '🍑' },
{ label: '🍒cherry | fruit', value: '🍒' },
{ label: '🍓berry | fruit', value: '🍓' },
{ label: '🥝food | fruit | kiwi', value: '🥝' },
{ label: '🍅fruit | vegetable', value: '🍅' },
{ label: '🥑avocado | food | fruit', value: '🥑' },
{ label: '🍆aubergine | vegetable', value: '🍆' },
{ label: '🥔food | potato | vegetable', value: '🥔' },
{ label: '🥕carrot | food | vegetable', value: '🥕' },
{ label: '🌽corn | ear | maize | maze', value: '🌽' },
{ label: '🌶hot | pepper', value: '🌶' },
{ label: '🥒cucumber | food| pickle | vegetable', value: '🥒' },
{ label: '🍄toadstool', value: '🍄' },
{ label: '🥜food | nut | peanut | vegetable', value: '🥜' },
{ label: '🌰plant', value: '🌰' },
{ label: '🍞loaf', value: '🍞' },
{ label: '🥐bread | crescent roll | croissant | food | french', value: '🥐' },
{ label: '🥖baguette | bread| food | french', value: '🥖' },
{ label: '🥞crêpe | food | hotcake | pancake', value: '🥞' },
{ label: '🧀cheese', value: '🧀' },
{ label: '🍖bone | meat', value: '🍖' },
{ label: '🍗bone | chicken | leg | poultry', value: '🍗' },
{ label: '🥓bacon | food | meat', value: '🥓' },
{ label: '🍔burger', value: '🍔' },
{ label: '🍟french | fries', value: '🍟' },
{ label: '🍕cheese | slice', value: '🍕' },
{ label: '🌭frankfurter | hotdog | sausage', value: '🌭' },
{ label: '🌮mexican', value: '🌮' },
{ label: '🌯mexican | wrap', value: '🌯' },
{ label: '🥙falafel | flatbread| food | gyro | kebab | stuffed', value: '🥙' },
{ label: '🥚egg | food', value: '🥚' },
{ label: '🍳egg | frying | pan', value: '🍳' },
{ label: '🥘casserole | food | paella | pan | shallow', value: '🥘' },
{ label: '🍲pot | stew', value: '🍲' },
{ label: '🥗food | green | salad', value: '🥗' },
{ label: '🍿popcorn', value: '🍿' },
{ label: '🍱bento | box', value: '🍱' },
{ label: '🍘cracker | rice', value: '🍘' },
{ label: '🍙ball | Japanese | rice', value: '🍙' },
{ label: '🍚cooked | rice', value: '🍚' },
{ label: '🍛curry | rice', value: '🍛' },
{ label: '🍜bowl | noodle | ramen | steaming', value: '🍜' },
{ label: '🍝pasta', value: '🍝' },
{ label: '🍠potato | roasted | sweet', value: '🍠' },
{ label: '🍢kebab | seafood| skewer | stick', value: '🍢' },
{ label: '🍣sushi', value: '🍣' },
{ label: '🍤fried | prawn | shrimp | tempura', value: '🍤' },
{ label: '🍥cake | fish | pastry | swirl', value: '🍥' },
{ label: '🍡dessert | Japanese | skewer | stick | sweet', value: '🍡' },
{ label: '🍦cream | dessert | ice | icecream | soft | sweet', value: '🍦' },
{ label: '🍧dessert | ice | shaved | sweet', value: '🍧' },
{ label: '🍨cream | dessert | ice | sweet', value: '🍨' },
{ label: '🍩dessert | donut | sweet', value: '🍩' },
{ label: '🍪dessert | sweet', value: '🍪' },
{ label: '🎂birthday | cake | celebration | dessert | pastry | sweet', value: '🎂' },
{ label: '🍰cake | dessert | pastry | slice | sweet', value: '🍰' },
{ label: '🍫bar | chocolate | dessert | sweet', value: '🍫' },
{ label: '🍬dessert | sweet', value: '🍬' },
{ label: '🍭candy | dessert | sweet', value: '🍭' },
{ label: '🍮dessert | pudding | sweet', value: '🍮' },
{ label: '🍯honey | honeypot | pot | sweet', value: '🍯' },
{ label: '🍼baby | bottle | drink | milk', value: '🍼' },
{ label: '🥛drink | glass | milk', value: '🥛' },
{ label: '☕beverage | coffee | drink | hot | steaming | tea', value: '☕' },
{ label: '🍵beverage | cup | drink | tea | teacup', value: '🍵' },
{ label: '🍶bar | beverage | bottle | cup | drink', value: '🍶' },
{ label: '🍾bar | bottle | cork| drink | popping', value: '🍾' },
{ label: '🍷bar | beverage | drink | glass | wine', value: '🍷' },
{ label: '🍸bar | cocktail | drink | glass', value: '🍸' },
{ label: '🍹bar | drink | tropical', value: '🍹' },
{ label: '🍺bar | beer | drink| mug', value: '🍺' },
{ label: '🍻bar | beer | clink | drink | mug', value: '🍻' },
{ label: '🥂celebrate | clink | drink | glass', value: '🥂' },
{ label: '🥃glass | liquor | shot | tumbler | whisky', value: '🥃' },
{ label: '🍽cooking | fork | knife | plate', value: '🍽' },
{ label: '🍴cooking | fork | knife', value: '🍴' },
{ label: '🥄spoon | tableware', value: '🥄' },
{ label: '🔪cooking | hocho | knife | tool | weapon', value: '🔪' },
{ label: '🏺Aquarius | cooking | drink | jug | tool | weapon | zodiac', value: '🏺' },
{ label: '🌍Africa | earth | Europe | globe | world', value: '🌍' },
{ label: '🌎Americas | earth| globe | world', value: '🌎' },
{ label: '🌏Asia | Australia | earth | globe | world', value: '🌏' },
{ label: '🌐earth | globe | meridians | world', value: '🌐' },
{ label: '🗺map | world', value: '🗺' },
{ label: '🗾Japan | map', value: '🗾' },
{ label: '🏔cold | mountain | snow', value: '🏔' },
{ label: '⛰mountain', value: '⛰' },
{ label: '🌋eruption | mountain', value: '🌋' },
{ label: '🗻fuji | mountain', value: '🗻' },
{ label: '🏕camping', value: '🏕' },
{ label: '🏖beach | umbrella', value: '🏖' },
{ label: '🏜desert', value: '🏜' },
{ label: '🏝desert | island', value: '🏝' },
{ label: '🏞park', value: '🏞' },
{ label: '🏟stadium', value: '🏟' },
{ label: '🏛classical', value: '🏛' },
{ label: '🏗construction', value: '🏗' },
{ label: '🏘house', value: '🏘' },
{ label: '🏙city', value: '🏙' },
{ label: '🏚derelict | house', value: '🏚' },
{ label: '🏠home | house', value: '🏠' },
{ label: '🏡garden | home | house', value: '🏡' },
{ label: '🏢building', value: '🏢' },
{ label: '🏣Japanese | post', value: '🏣' },
{ label: '🏤European | post', value: '🏤' },
{ label: '🏥doctor | medicine', value: '🏥' },
{ label: '🏦building', value: '🏦' },
{ label: '🏨building', value: '🏨' },
{ label: '🏩hotel | love', value: '🏩' },
{ label: '🏪convenience | store', value: '🏪' },
{ label: '🏫building', value: '🏫' },
{ label: '🏬department | store', value: '🏬' },
{ label: '🏭building', value: '🏭' },
{ label: '🏯castle | Japanese', value: '🏯' },
{ label: '🏰European', value: '🏰' },
{ label: '💒chapel | romance', value: '💒' },
{ label: '🗼Tokyo | tower', value: '🗼' },
{ label: '🗽liberty | statue', value: '🗽' },
{ label: '⛪Christian | cross| religion', value: '⛪' },
{ label: '🕌islam | Muslim | religion', value: '🕌' },
{ label: '🕍Jew | Jewish | religion | temple', value: '🕍' },
{ label: '⛩religion | shinto | shrine', value: '⛩' },
{ label: '🕋islam | Muslim | religion', value: '🕋' },
{ label: '⛲fountain', value: '⛲' },
{ label: '⛺camping', value: '⛺' },
{ label: '🌁fog', value: '🌁' },
{ label: '🌃night | star', value: '🌃' },
{ label: '🌄morning | mountain | sun | sunrise', value: '🌄' },
{ label: '🌅morning | sun', value: '🌅' },
{ label: '🌆city | dusk | evening | landscape | sun | sunset', value: '🌆' },
{ label: '🌇dusk | sun', value: '🌇' },
{ label: '🌉bridge | night', value: '🌉' },
{ label: '♨hot | hotsprings | springs | steaming', value: '♨' },
{ label: '🌌space', value: '🌌' },
{ label: '🎠carousel | horse', value: '🎠' },
{ label: '🎡amusement park| ferris | wheel', value: '🎡' },
{ label: '🎢amusement park| coaster | roller', value: '🎢' },
{ label: '💈barber | haircut | pole', value: '💈' },
{ label: '🎪circus | tent', value: '🎪' },
{ label: '🎭art | mask | performing | theater | theatre', value: '🎭' },
{ label: '🖼art | frame | museum | painting | picture', value: '🖼' },
{ label: '🎨art | museum | painting | palette', value: '🎨' },
{ label: '🎰game | slot', value: '🎰' },
{ label: '🚂engine | railway | steam | train', value: '🚂' },
{ label: '🚃car | electric | railway | train | tram | trolleybus', value: '🚃' },
{ label: '🚄railway | shinkansen | speed | train', value: '🚄' },
{ label: '🚅bullet | railway | shinkansen | speed | train', value: '🚅' },
{ label: '🚆railway', value: '🚆' },
{ label: '🚇subway', value: '🚇' },
{ label: '🚈railway', value: '🚈' },
{ label: '🚉railway | train', value: '🚉' },
{ label: '🚊trolleybus', value: '🚊' },
{ label: '🚝vehicle', value: '🚝' },
{ label: '🚞car | mountain | railway', value: '🚞' },
{ label: '🚋car | tram | trolleybus', value: '🚋' },
{ label: '🚌vehicle', value: '🚌' },
{ label: '🚍bus | oncoming', value: '🚍' },
{ label: '🚎bus | tram | trolley', value: '🚎' },
{ label: '🚐bus', value: '🚐' },
{ label: '🚑vehicle', value: '🚑' },
{ label: '🚒engine | fire | truck', value: '🚒' },
{ label: '🚓car | patrol | police', value: '🚓' },
{ label: '🚔car | oncoming | police', value: '🚔' },
{ label: '🚕vehicle', value: '🚕' },
{ label: '🚖oncoming | taxi', value: '🚖' },
{ label: '🚗car', value: '🚗' },
{ label: '🚘automobile | car| oncoming', value: '🚘' },
{ label: '🚙recreational | sport utility', value: '🚙' },
{ label: '🚚delivery | truck', value: '🚚' },
{ label: '🚛lorry | semi | truck', value: '🚛' },
{ label: '🚜vehicle', value: '🚜' },
{ label: '🚲bike', value: '🚲' },
{ label: '🛴kick | scooter', value: '🛴' },
{ label: '🛵motor | scooter', value: '🛵' },
{ label: '🚏bus | busstop | stop', value: '🚏' },
{ label: '🛣highway | road', value: '🛣' },
{ label: '🛤railway | train', value: '🛤' },
{ label: '⛽fuel | fuelpump | gas | pump | station', value: '⛽' },
{ label: '🚨beacon | car | light | police | revolving', value: '🚨' },
{ label: '🚥light | signal | traffic', value: '🚥' },
{ label: '🚦light | signal | traffic', value: '🚦' },
{ label: '🚧barrier', value: '🚧' },
{ label: '🛑octagonal | sign | stop', value: '🛑' },
{ label: '⚓ship | tool', value: '⚓' },
{ label: '⛵boat | resort | sea | yacht', value: '⛵' },
{ label: '🛶boat | canoe', value: '🛶' },
{ label: '🚤boat', value: '🚤' },
{ label: '🛳passenger | ship', value: '🛳' },
{ label: '⛴boat | passenger', value: '⛴' },
{ label: '🛥boat | motorboat', value: '🛥' },
{ label: '🚢boat | passenger', value: '🚢' },
{ label: '✈aeroplane | airplane', value: '✈' },
{ label: '🛩aeroplane | airplane', value: '🛩' },
{ label: '🛫aeroplane | airplane | check-in | departure | departures', value: '🛫' },
{ label: '🛬aeroplane | airplane | arrivals| arriving | landing', value: '🛬' },
{ label: '💺chair', value: '💺' },
{ label: '🚁vehicle', value: '🚁' },
{ label: '🚟railway | suspension', value: '🚟' },
{ label: '🚠cable | gondola | mountain', value: '🚠' },
{ label: '🚡aerial | cable | car | gondola | tramway', value: '🚡' },
{ label: '🚀space', value: '🚀' },
{ label: '🛰space', value: '🛰' },
{ label: '🛎bell | bellhop | hotel', value: '🛎' },
{ label: '🚪door', value: '🚪' },
{ label: '🛌hotel | sleep', value: '🛌' },
{ label: '🛏hotel | sleep', value: '🛏' },
{ label: '🛋couch | hotel | lamp', value: '🛋' },
{ label: '🚽toilet', value: '🚽' },
{ label: '🚿water', value: '🚿' },
{ label: '🛀bath | bathtub', value: '🛀' },
{ label: '🛀🏻bath | bathtub | light skin tone', value: '🛀🏻' },
{ label: '🛀🏼bath | bathtub | medium-light skin tone', value: '🛀🏼' },
{ label: '🛀🏽bath | bathtub | medium skin tone', value: '🛀🏽' },
{ label: '🛀🏾bath | bathtub | medium-dark skin tone', value: '🛀🏾' },
{ label: '🛀🏿bath | bathtub | dark skin tone', value: '🛀🏿' },
{ label: '🛁bath', value: '🛁' },
{ label: '⌛sand | timer', value: '⌛' },
{ label: '⏳hourglass | sand| timer', value: '⏳' },
{ label: '⌚clock', value: '⌚' },
{ label: '⏰alarm | clock', value: '⏰' },
{ label: '⏱clock', value: '⏱' },
{ label: '⏲clock | timer', value: '⏲' },
{ label: '🕰clock', value: '🕰' },
{ label: '🕛00 | 12 | 12:00 | clock | o’clock | twelve', value: '🕛' },
{ label: '🕧12 | 12:30 | 30 | clock | thirty | twelve', value: '🕧' },
{ label: '🕐00 | 1 | 1:00 | clock | o’clock | one', value: '🕐' },
{ label: '🕜1 | 1:30 | 30 | clock | one | thirty', value: '🕜' },
{ label: '🕑00 | 2 | 2:00 | clock | o’clock | two', value: '🕑' },
{ label: '🕝2 | 2:30 | 30 | clock | thirty | two', value: '🕝' },
{ label: '🕒00 | 3 | 3:00 | clock | o’clock | three', value: '🕒' },
{ label: '🕞3 | 3:30 | 30 | clock | thirty | three', value: '🕞' },
{ label: '🕓00 | 4 | 4:00 | clock | four | o’clock', value: '🕓' },
{ label: '🕟30 | 4 | 4:30 | clock | four | thirty', value: '🕟' },
{ label: '🕔00 | 5 | 5:00 | clock | five | o’clock', value: '🕔' },
{ label: '🕠30 | 5 | 5:30 | clock | five | thirty', value: '🕠' },
{ label: '🕕00 | 6 | 6:00 | clock | o’clock | six', value: '🕕' },
{ label: '🕡30 | 6 | 6:30 | clock | six | thirty', value: '🕡' },
{ label: '🕖00 | 7 | 7:00 | clock | o’clock | seven', value: '🕖' },
{ label: '🕢30 | 7 | 7:30 | clock | seven | thirty', value: '🕢' },
{ label: '🕗00 | 8 | 8:00 | clock | eight | o’clock', value: '🕗' },
{ label: '🕣30 | 8 | 8:30 | clock | eight | thirty', value: '🕣' },
{ label: '🕘00 | 9 | 9:00 | clock | nine | o’clock', value: '🕘' },
{ label: '🕤30 | 9 | 9:30 | clock | nine | thirty', value: '🕤' },
{ label: '🕙00 | 10 | 10:00 | clock | o’clock | ten', value: '🕙' },
{ label: '🕥10 | 10:30 | 30 | clock | ten | thirty', value: '🕥' },
{ label: '🕚00 | 11 | 11:00 | clock | eleven | o’clock', value: '🕚' },
{ label: '🕦11 | 11:30 | 30 | clock | eleven | thirty', value: '🕦' },
{ label: '🌑dark | moon', value: '🌑' },
{ label: '🌒crescent | moon| waxing', value: '🌒' },
{ label: '🌓moon | quarter', value: '🌓' },
{ label: '🌔gibbous | moon | waxing', value: '🌔' },
{ label: '🌕full | moon', value: '🌕' },
{ label: '🌖gibbous | moon | waning', value: '🌖' },
{ label: '🌗moon | quarter', value: '🌗' },
{ label: '🌘crescent | moon| waning', value: '🌘' },
{ label: '🌙crescent | moon', value: '🌙' },
{ label: '🌚face | moon', value: '🌚' },
{ label: '🌛face | moon | quarter', value: '🌛' },
{ label: '🌜face | moon | quarter', value: '🌜' },
{ label: '🌡weather', value: '🌡' },
{ label: '☀bright | rays | sunny', value: '☀' },
{ label: '🌝bright | face | full| moon', value: '🌝' },
{ label: '🌞bright | face | sun', value: '🌞' },
{ label: '⭐star', value: '⭐' },
{ label: '🌟glittery | glow | shining | sparkle| star', value: '🌟' },
{ label: '🌠falling | shooting| star', value: '🌠' },
{ label: '☁weather', value: '☁' },
{ label: '⛅cloud | sun', value: '⛅' },
{ label: '⛈cloud | rain | thunder', value: '⛈' },
{ label: '🌤cloud | sun', value: '🌤' },
{ label: '🌥cloud | sun', value: '🌥' },
{ label: '🌦cloud | rain | sun', value: '🌦' },
{ label: '🌧cloud | rain', value: '🌧' },
{ label: '🌨cloud | cold | snow', value: '🌨' },
{ label: '🌩cloud | lightning', value: '🌩' },
{ label: '🌪cloud | whirlwind', value: '🌪' },
{ label: '🌫cloud', value: '🌫' },
{ label: '🌬blow | cloud | face | wind', value: '🌬' },
{ label: '🌀dizzy | twister | typhoon', value: '🌀' },
{ label: '🌈rain', value: '🌈' },
{ label: '🌂clothing | rain | umbrella', value: '🌂' },
{ label: '☂clothing | rain', value: '☂' },
{ label: '☔clothing | drop | rain | umbrella', value: '☔' },
{ label: '⛱rain | sun | umbrella', value: '⛱' },
{ label: '⚡danger | electric| electricity | lightning | voltage | zap', value: '⚡' },
{ label: '❄cold | snow', value: '❄' },
{ label: '☃cold | snow', value: '☃' },
{ label: '⛄cold | snow | snowman', value: '⛄' },
{ label: '☄space', value: '☄' },
{ label: '🔥flame | tool', value: '🔥' },
{ label: '💧cold | comic | drop | sweat', value: '💧' },
{ label: '🌊ocean | water | wave', value: '🌊' },
{ label: '🎃celebration | halloween | jack| lantern', value: '🎃' },
{ label: '🎄celebration | Christmas | tree', value: '🎄' },
{ label: '🎆celebration', value: '🎆' },
{ label: '🎇celebration | fireworks | sparkle', value: '🎇' },
{ label: '✨sparkle | star', value: '✨' },
{ label: '🎈celebration', value: '🎈' },
{ label: '🎉celebration | party | popper | tada', value: '🎉' },
{ label: '🎊ball | celebration| confetti', value: '🎊' },
{ label: '🎋banner | celebration | Japanese | tree', value: '🎋' },
{ label: '🎍bamboo | celebration | Japanese | pine', value: '🎍' },
{ label: '🎎celebration | doll| festival | Japanese', value: '🎎' },
{ label: '🎏carp | celebration | streamer', value: '🎏' },
{ label: '🎐bell | celebration| chime | wind', value: '🎐' },
{ label: '🎑celebration | ceremony | moon', value: '🎑' },
{ label: '🎀celebration', value: '🎀' },
{ label: '🎁box | celebration| gift | present | wrapped', value: '🎁' },
{ label: '🎗celebration | reminder | ribbon', value: '🎗' },
{ label: '🎟admission | ticket', value: '🎟' },
{ label: '🎫admission', value: '🎫' },
{ label: '🎖celebration | medal | military', value: '🎖' },
{ label: '🏆prize', value: '🏆' },
{ label: '🏅medal', value: '🏅' },
{ label: '🥇first | gold | medal', value: '🥇' },
{ label: '🥈medal | second | silver', value: '🥈' },
{ label: '🥉bronze | medal | third', value: '🥉' },
{ label: '⚽ball | football | soccer', value: '⚽' },
{ label: '⚾ball', value: '⚾' },
{ label: '🏀ball | hoop', value: '🏀' },
{ label: '🏐ball | game', value: '🏐' },
{ label: '🏈american | ball | football', value: '🏈' },
{ label: '🏉ball | football | rugby', value: '🏉' },
{ label: '🎾ball | racquet', value: '🎾' },
{ label: '🎱8 | 8 ball | ball | billiard | eight | game', value: '🎱' },
{ label: '🎳ball | game', value: '🎳' },
{ label: '🏏ball | bat | game', value: '🏏' },
{ label: '🏑ball | field | game| hockey | stick', value: '🏑' },
{ label: '🏒game | hockey | ice | puck | stick', value: '🏒' },
{ label: '🏓ball | bat | game | paddle | ping pong | table tennis', value: '🏓' },
{ label: '🏸birdie | game | racquet | shuttlecock', value: '🏸' },
{ label: '🥊boxing | glove', value: '🥊' },
{ label: '🥋judo | karate | martial arts | taekwondo | uniform', value: '🥋' },
{ label: '🥅goal | net', value: '🥅' },
{ label: '🎯bull | bullseye | dart | eye | game| hit | target', value: '🎯' },
{ label: '⛳golf | hole', value: '⛳' },
{ label: '⛸ice | skate', value: '⛸' },
{ label: '🎣fish | pole', value: '🎣' },
{ label: '🎽athletics | running | sash | shirt', value: '🎽' },
{ label: '🎿ski | snow', value: '🎿' },
{ label: '🎮controller | game', value: '🎮' },
{ label: '🕹game | video game', value: '🕹' },
{ label: '🎲dice | die | game', value: '🎲' },
{ label: '♠card | game', value: '♠' },
{ label: '♥card | game', value: '♥' },
{ label: '♦card | game', value: '♦' },
{ label: '♣card | game', value: '♣' },
{ label: '🃏card | game | wildcard', value: '🃏' },
{ label: '🀄game | mahjong| red', value: '🀄' },
{ label: '🎴card | flower | game | Japanese | playing', value: '🎴' },
{ label: '🔇mute | quiet | silent | speaker', value: '🔇' },
{ label: '🔈soft', value: '🔈' },
{ label: '🔉medium', value: '🔉' },
{ label: '🔊loud', value: '🔊' },
{ label: '📢loud | public address', value: '📢' },
{ label: '📣cheering', value: '📣' },
{ label: '📯horn | post | postal', value: '📯' },
{ label: '🔔bell', value: '🔔' },
{ label: '🔕bell | forbidden | mute | no | not | prohibited | quiet| silent', value: '🔕' },
{ label: '🎼music | score', value: '🎼' },
{ label: '🎵music | note', value: '🎵' },
{ label: '🎶music | note | notes', value: '🎶' },
{ label: '🎙mic | microphone| music | studio', value: '🎙' },
{ label: '🎚level | music | slider', value: '🎚' },
{ label: '🎛control | knobs | music', value: '🎛' },
{ label: '🎤karaoke | mic', value: '🎤' },
{ label: '🎧earbud', value: '🎧' },
{ label: '📻video', value: '📻' },
{ label: '🎷instrument | music | sax', value: '🎷' },
{ label: '🎸instrument | music', value: '🎸' },
{ label: '🎹instrument | keyboard | music| piano', value: '🎹' },
{ label: '🎺instrument | music', value: '🎺' },
{ label: '🎻instrument | music', value: '🎻' },
{ label: '🥁drum | drumsticks | music', value: '🥁' },
{ label: '📱cell | mobile | phone | telephone', value: '📱' },
{ label: '📲arrow | call | cell| mobile | phone | receive | telephone', value: '📲' },
{ label: '☎phone', value: '☎' },
{ label: '📞phone | receiver| telephone', value: '📞' },
{ label: '📟pager', value: '📟' },
{ label: '📠fax', value: '📠' },
{ label: '🔋battery', value: '🔋' },
{ label: '🔌electric | electricity | plug', value: '🔌' },
{ label: '💻computer | pc | personal', value: '💻' },
{ label: '🖥computer | desktop', value: '🖥' },
{ label: '🖨computer', value: '🖨' },
{ label: '⌨computer', value: '⌨' },
{ label: '🖱computer', value: '🖱' },
{ label: '🖲computer', value: '🖲' },
{ label: '💽computer | disk | minidisk | optical', value: '💽' },
{ label: '💾computer | disk | floppy', value: '💾' },
{ label: '💿cd | computer | disk | optical', value: '💿' },
{ label: '📀blu-ray | computer | disk | dvd | optical', value: '📀' },
{ label: '🎥camera | cinema| movie', value: '🎥' },
{ label: '🎞cinema | film | frames | movie', value: '🎞' },
{ label: '📽cinema | film | movie | projector| video', value: '📽' },
{ label: '🎬clapper | movie', value: '🎬' },
{ label: '📺tv | video', value: '📺' },
{ label: '📷video', value: '📷' },
{ label: '📸camera | flash | video', value: '📸' },
{ label: '📹camera | video', value: '📹' },
{ label: '📼tape | vhs | video', value: '📼' },
{ label: '🔍glass | magnifying | search | tool', value: '🔍' },
{ label: '🔎glass | magnifying | search | tool', value: '🔎' },
{ label: '🔬science | tool', value: '🔬' },
{ label: '🔭science | tool', value: '🔭' },
{ label: '📡antenna | dish | satellite', value: '📡' },
{ label: '🕯light', value: '🕯' },
{ label: '💡bulb | comic | electric | idea | light', value: '💡' },
{ label: '🔦electric | light | tool | torch', value: '🔦' },
{ label: '🏮bar | Japanese | lantern | light | red', value: '🏮' },
{ label: '📔book | cover | decorated | notebook', value: '📔' },
{ label: '📕book | closed', value: '📕' },
{ label: '📖book', value: '📖' },
{ label: '📗book | green', value: '📗' },
{ label: '📘blue | book', value: '📘' },
{ label: '📙book | orange', value: '📙' },
{ label: '📚book', value: '📚' },
{ label: '📓notebook', value: '📓' },
{ label: '📒notebook', value: '📒' },
{ label: '📃curl | document | page', value: '📃' },
{ label: '📜paper', value: '📜' },
{ label: '📄document | page', value: '📄' },
{ label: '📰news | paper', value: '📰' },
{ label: '🗞news | newspaper | paper | rolled', value: '🗞' },
{ label: '📑bookmark | mark| marker | tabs', value: '📑' },
{ label: '🔖mark', value: '🔖' },
{ label: '🏷label', value: '🏷' },
{ label: '💰bag | dollar | money | moneybag', value: '💰' },
{ label: '💴bank | banknote| bill | currency | money | note | yen', value: '💴' },
{ label: '💵bank | banknote| bill | currency | dollar | money | note', value: '💵' },
{ label: '💶bank | banknote| bill | currency | euro | money | note', value: '💶' },
{ label: '💷bank | banknote| bill | currency | money | note | pound', value: '💷' },
{ label: '💸bank | banknote| bill | dollar | fly | money | note | wings', value: '💸' },
{ label: '💳bank | card | credit | money', value: '💳' },
{ label: '💹bank | chart | currency | graph| growth | market| money | rise | trend | upward | yen', value: '💹' },
{ label: '💱bank | currency | exchange | money', value: '💱' },
{ label: '💲currency | dollar| money', value: '💲' },
{ label: '✉email | letter', value: '✉' },
{ label: '📧email | letter | mail', value: '📧' },
{ label: '📨e-mail | email | envelope | incoming | letter | mail | receive', value: '📨' },
{ label: '📩arrow | down | e-mail | email | envelope | letter| mail | outgoing | sent', value: '📩' },
{ label: '📤box | letter | mail| outbox | sent | tray', value: '📤' },
{ label: '📥box | inbox | letter | mail | receive | tray', value: '📥' },
{ label: '📦box | parcel', value: '📦' },
{ label: '📫closed | mail | mailbox | postbox', value: '📫' },
{ label: '📪closed | lowered| mail | mailbox | postbox', value: '📪' },
{ label: '📬mail | mailbox | postbox', value: '📬' },
{ label: '📭lowered | mail | mailbox | postbox', value: '📭' },
{ label: '📮mail | mailbox', value: '📮' },
{ label: '🗳ballot | box', value: '🗳' },
{ label: '✏pencil', value: '✏' },
{ label: '✒nib | pen', value: '✒' },
{ label: '🖋fountain | pen', value: '🖋' },
{ label: '🖊ballpoint', value: '🖊' },
{ label: '🖌painting', value: '🖌' },
{ label: '🖍crayon', value: '🖍' },
{ label: '📝pencil', value: '📝' },
{ label: '💼briefcase', value: '💼' },
{ label: '📁file | folder', value: '📁' },
{ label: '📂file | folder', value: '📂' },
{ label: '🗂card | dividers | index', value: '🗂' },
{ label: '📅date', value: '📅' },
{ label: '📆calendar', value: '📆' },
{ label: '🗒note | pad | spiral', value: '🗒' },
{ label: '🗓calendar | pad | spiral', value: '🗓' },
{ label: '📇card | index | rolodex', value: '📇' },
{ label: '📈chart | graph | growth | trend | upward', value: '📈' },
{ label: '📉chart | down | graph | trend', value: '📉' },
{ label: '📊bar | chart | graph', value: '📊' },
{ label: '📋clipboard', value: '📋' },
{ label: '📌pin', value: '📌' },
{ label: '📍pin | pushpin', value: '📍' },
{ label: '📎paperclip', value: '📎' },
{ label: '🖇link | paperclip', value: '🖇' },
{ label: '📏ruler | straight edge', value: '📏' },
{ label: '📐ruler | set | triangle', value: '📐' },
{ label: '✂cutting | tool', value: '✂' },
{ label: '🗃box | card | file', value: '🗃' },
{ label: '🗄cabinet | file | filing', value: '🗄' },
{ label: '🗑wastebasket', value: '🗑' },
{ label: '🔒closed', value: '🔒' },
{ label: '🔓lock | unlock', value: '🔓' },
{ label: '🔏ink | lock | nib | pen | privacy', value: '🔏' },
{ label: '🔐closed | key | lock | secure', value: '🔐' },
{ label: '🔑lock | password', value: '🔑' },
{ label: '🗝clue | key | lock | old', value: '🗝' },
{ label: '🔨tool', value: '🔨' },
{ label: '⛏mining | tool', value: '⛏' },
{ label: '⚒hammer | pick | tool', value: '⚒' },
{ label: '🛠hammer | spanner | tool | wrench', value: '🛠' },
{ label: '🗡knife | weapon', value: '🗡' },
{ label: '⚔crossed | swords| weapon', value: '⚔' },
{ label: '🔫gun | handgun | revolver | tool | weapon', value: '🔫' },
{ label: '🏹archer | archery | arrow | bow | Sagittarius | tool| weapon | zodiac', value: '🏹' },
{ label: '🛡weapon', value: '🛡' },
{ label: '🔧spanner | tool | wrench', value: '🔧' },
{ label: '🔩bolt | nut | tool', value: '🔩' },
{ label: '⚙tool', value: '⚙' },
{ label: '🗜compress | tool | vice', value: '🗜' },
{ label: '⚗chemistry | tool', value: '⚗' },
{ label: '⚖balance | justice| Libra | scales | tool | weight | zodiac', value: '⚖' },
{ label: '🔗link', value: '🔗' },
{ label: '⛓chain', value: '⛓' },
{ label: '💉doctor | medicine| needle | shot | sick | tool', value: '💉' },
{ label: '💊doctor | medicine| sick', value: '💊' },
{ label: '🚬smoking', value: '🚬' },
{ label: '⚰death', value: '⚰' },
{ label: '⚱ashes | death | funeral | urn', value: '⚱' },
{ label: '🗿face | moyai | statue', value: '🗿' },
{ label: '🛢drum | oil', value: '🛢' },
{ label: '🔮ball | crystal | fairy tale | fantasy | fortune| tool', value: '🔮' },
{ label: '🛒cart | shopping | trolley', value: '🛒' },
{ label: '🏧atm | automated| bank | teller', value: '🏧' },
{ label: '🚮litter | litter bin', value: '🚮' },
{ label: '🚰drinking | potable| water', value: '🚰' },
{ label: '♿access', value: '♿' },
{ label: '🚹lavatory | man | restroom | wc', value: '🚹' },
{ label: '🚺lavatory | restroom | wc | woman', value: '🚺' },
{ label: '🚻lavatory | restroom | WC', value: '🚻' },
{ label: '🚼baby | changing', value: '🚼' },
{ label: '🚾closet | lavatory | restroom | water| wc', value: '🚾' },
{ label: '🛂control | passport', value: '🛂' },
{ label: '🛃customs', value: '🛃' },
{ label: '🛄baggage | claim', value: '🛄' },
{ label: '🛅baggage | locker| luggage', value: '🛅' },
{ label: '⚠warning', value: '⚠' },
{ label: '🚸child | crossing | pedestrian | traffic', value: '🚸' },
{ label: '⛔entry | forbidden| no | not | prohibited | traffic', value: '⛔' },
{ label: '🚫entry | forbidden| no | not', value: '🚫' },
{ label: '🚳bicycle | bike | forbidden | no | not | prohibited', value: '🚳' },
{ label: '🚭forbidden | no | not | prohibited | smoking', value: '🚭' },
{ label: '🚯forbidden | litter | no | not | prohibited', value: '🚯' },
{ label: '🚱non-drinking | non-potable | water', value: '🚱' },
{ label: '🚷forbidden | no | not | pedestrian | prohibited', value: '🚷' },
{ label: '📵cell | forbidden | mobile | no | not | phone | prohibited | telephone', value: '📵' },
{ label: '🔞18 | age restriction | eighteen | forbidden | no | not | prohibited | underage', value: '🔞' },
{ label: '☢radioactive | sign', value: '☢' },
{ label: '☣biohazard | sign', value: '☣' },
{ label: '⬆arrow | cardinal | direction | north', value: '⬆' },
{ label: '↗arrow | direction| intercardinal | northeast', value: '↗' },
{ label: '➡arrow | cardinal | direction | east', value: '➡' },
{ label: '↘arrow | direction| intercardinal | southeast', value: '↘' },
{ label: '⬇arrow | cardinal | direction | down | south', value: '⬇' },
{ label: '↙arrow | direction| intercardinal | southwest', value: '↙' },
{ label: '⬅arrow | cardinal | direction | west', value: '⬅' },
{ label: '↖arrow | direction| intercardinal | northwest', value: '↖' },
{ label: '↕arrow', value: '↕' },
{ label: '↔arrow', value: '↔' },
{ label: '↩arrow', value: '↩' },
{ label: '↪arrow', value: '↪' },
{ label: '⤴arrow', value: '⤴' },
{ label: '⤵arrow | down', value: '⤵' },
{ label: '🔃arrow | clockwise| reload', value: '🔃' },
{ label: '🔄anticlockwise | arrow | counterclockwise| withershins', value: '🔄' },
{ label: '🔙arrow | back', value: '🔙' },
{ label: '🔚arrow | end', value: '🔚' },
{ label: '🔛arrow | mark | on', value: '🔛' },
{ label: '🔜arrow | soon', value: '🔜' },
{ label: '🔝arrow | top | up', value: '🔝' },
{ label: '🛐religion | worship', value: '🛐' },
{ label: '⚛atheist | atom', value: '⚛' },
{ label: '🕉Hindu | religion', value: '🕉' },
{ label: '✡David | Jew | Jewish | religion| star', value: '✡' },
{ label: '☸Buddhist | dharma | religion| wheel', value: '☸' },
{ label: '☯religion | tao | taoist | yang | yin', value: '☯' },
{ label: '☦Christian | cross| religion', value: '☦' },
{ label: '☪islam | Muslim | religion', value: '☪' },
{ label: '☮peace', value: '☮' },
{ label: '🕎candelabrum | candlestick | religion', value: '🕎' },
{ label: '🔯fortune | star', value: '🔯' },
{ label: '♈ram | zodiac', value: '♈' },
{ label: '♉bull | ox | zodiac', value: '♉' },
{ label: '♊twins | zodiac', value: '♊' },
{ label: '♋crab | zodiac', value: '♋' },
{ label: '♌lion | zodiac', value: '♌' },
{ label: '♍zodiac', value: '♍' },
{ label: '♎balance | justice| scales | zodiac', value: '♎' },
{ label: '♏scorpio | scorpion | zodiac', value: '♏' },
{ label: '♐archer | zodiac', value: '♐' },
{ label: '♑goat | zodiac', value: '♑' },
{ label: '♒bearer | water | zodiac', value: '♒' },
{ label: '♓fish | zodiac', value: '♓' },
{ label: '⛎bearer | serpent | snake | zodiac', value: '⛎' },
{ label: '🔀arrow | crossed', value: '🔀' },
{ label: '🔁arrow | clockwise| repeat', value: '🔁' },
{ label: '🔂arrow | clockwise| once', value: '🔂' },
{ label: '▶arrow | play | right | triangle', value: '▶' },
{ label: '⏩arrow | double | fast | forward', value: '⏩' },
{ label: '⏭arrow | next scene | next track | triangle', value: '⏭' },
{ label: '⏯arrow | pause | play | right | triangle', value: '⏯' },
{ label: '◀arrow | left | reverse | triangle', value: '◀' },
{ label: '⏪arrow | double | rewind', value: '⏪' },
{ label: '⏮arrow | previous scene | previous track | triangle', value: '⏮' },
{ label: '🔼arrow | button | red', value: '🔼' },
{ label: '⏫arrow | double', value: '⏫' },
{ label: '🔽arrow | button | down | red', value: '🔽' },
{ label: '⏬arrow | double | down', value: '⏬' },
{ label: '⏸bar | double | pause | vertical', value: '⏸' },
{ label: '⏹square | stop', value: '⏹' },
{ label: '⏺circle | record', value: '⏺' },
{ label: '🎦camera | film | movie', value: '🎦' },
{ label: '🔅brightness | dim | low', value: '🔅' },
{ label: '🔆bright | brightness', value: '🔆' },
{ label: '📶antenna | bar | cell | mobile | phone | signal | telephone', value: '📶' },
{ label: '📳cell | mobile | mode | phone | telephone | vibration', value: '📳' },
{ label: '📴cell | mobile | off| phone | telephone', value: '📴' },
{ label: '♻recycle', value: '♻' },
{ label: '📛badge | name', value: '📛' },
{ label: '⚜fleur-de-lis', value: '⚜' },
{ label: '🔰beginner | chevron | green | Japanese | leaf | tool | yellow', value: '🔰' },
{ label: '🔱anchor | emblem| ship | tool | trident', value: '🔱' },
{ label: '⭕circle | o', value: '⭕' },
{ label: '✅check | mark', value: '✅' },
{ label: '☑ballot | box | check', value: '☑' },
{ label: '✔check | mark', value: '✔' },
{ label: '✖cancel | multiplication | multiply | x', value: '✖' },
{ label: '❌cancel | mark | multiplication | multiply | x', value: '❌' },
{ label: '❎mark | square', value: '❎' },
{ label: '➕math | plus', value: '➕' },
{ label: '➖math | minus', value: '➖' },
{ label: '➗division | math', value: '➗' },
{ label: '➰curl | loop', value: '➰' },
{ label: '➿curl | double | loop', value: '➿' },
{ label: '〽mark | part', value: '〽' },
{ label: '✳asterisk', value: '✳' },
{ label: '✴star', value: '✴' },
{ label: '❇sparkle', value: '❇' },
{ label: '‼bangbang | exclamation | mark | punctuation', value: '‼' },
{ label: '⁉exclamation | interrobang | mark | punctuation | question', value: '⁉' },
{ label: '❓mark | punctuation | question', value: '❓' },
{ label: '❔mark | outlined | punctuation | question', value: '❔' },
{ label: '❕exclamation | mark | outlined | punctuation', value: '❕' },
{ label: '❗exclamation | mark | punctuation', value: '❗' },
{ label: '〰dash | punctuation | wavy', value: '〰' },
{ label: '#️⃣keycap', value: '#️⃣' },
{ label: '*️⃣keycap', value: '*️⃣' },
{ label: '0️⃣keycap', value: '0️⃣' },
{ label: '1️⃣keycap', value: '1️⃣' },
{ label: '2️⃣keycap', value: '2️⃣' },
{ label: '3️⃣keycap', value: '3️⃣' },
{ label: '4️⃣keycap', value: '4️⃣' },
{ label: '5️⃣keycap', value: '5️⃣' },
{ label: '6️⃣keycap', value: '6️⃣' },
{ label: '7️⃣keycap', value: '7️⃣' },
{ label: '8️⃣keycap', value: '8️⃣' },
{ label: '9️⃣keycap', value: '9️⃣' },
{ label: '🔟keycap 10', value: '🔟' },
{ label: '💯100 | full | hundred | score', value: '💯' },
{ label: '🔠ABCD | input | latin | letters | uppercase', value: '🔠' },
{ label: '🔡abcd | input | latin | letters | lowercase', value: '🔡' },
{ label: '🔢1234 | input | numbers', value: '🔢' },
{ label: '🔣〒♪&% | input', value: '🔣' },
{ label: '🔤abc | alphabet | input | latin | letters', value: '🔤' },
{ label: '🅰a | blood type', value: '🅰' },
{ label: '🆎ab | blood type', value: '🆎' },
{ label: '🅱b | blood type', value: '🅱' },
{ label: '🆑cl', value: '🆑' },
{ label: '🆒cool', value: '🆒' },
{ label: '🆓free', value: '🆓' },
{ label: 'ℹi | information', value: 'ℹ' },
{ label: '🆔id | identity', value: '🆔' },
{ label: 'Ⓜcircle | m', value: 'Ⓜ' },
{ label: '🆕new', value: '🆕' },
{ label: '🆖ng', value: '🆖' },
{ label: '🅾blood type | o', value: '🅾' },
{ label: '🆗OK', value: '🆗' },
{ label: '🅿parking', value: '🅿' },
{ label: '🆘help | sos', value: '🆘' },
{ label: '🆙mark | up', value: '🆙' },
{ label: '🆚versus | vs', value: '🆚' },
{ label: '🈁“here” | Japanese | katakana | ココ', value: '🈁' },
{ label: '🈂“service charge”| Japanese | katakana | サ', value: '🈂' },
{ label: '🈷“monthly amount” | ideograph | Japanese | 月', value: '🈷' },
{ label: '🈶“not free of charge” | ideograph | Japanese | 有', value: '🈶' },
{ label: '🈯“reserved” | ideograph | Japanese | 指', value: '🈯' },
{ label: '🉐“bargain” | ideograph | Japanese | 得', value: '🉐' },
{ label: '🈹“discount” | ideograph | Japanese | 割', value: '🈹' },
{ label: '🈚“free of charge” | ideograph | Japanese | 無', value: '🈚' },
{ label: '🈲“prohibited” | ideograph | Japanese | 禁', value: '🈲' },
{ label: '🉑“acceptable” | ideograph | Japanese | 可', value: '🉑' },
{ label: '🈸“application” | ideograph | Japanese | 申', value: '🈸' },
{ label: '🈴“passing grade” | ideograph | Japanese | 合', value: '🈴' },
{ label: '🈳“vacancy” | ideograph | Japanese | 空', value: '🈳' },
{ label: '㊗“congratulations”| ideograph | Japanese | 祝', value: '㊗' },
{ label: '㊙“secret” | ideograph | Japanese | 秘', value: '㊙' },
{ label: '🈵“no vacancy” | ideograph | Japanese | 満', value: '🈵' },
{ label: '▪geometric | square', value: '▪' },
{ label: '▫geometric | square', value: '▫' },
{ label: '◻geometric | square', value: '◻' },
{ label: '◼geometric | square', value: '◼' },
{ label: '◽geometric | square', value: '◽' },
{ label: '◾geometric | square', value: '◾' },
{ label: '⬛geometric | square', value: '⬛' },
{ label: '⬜geometric | square', value: '⬜' },
{ label: '🔶diamond | geometric | orange', value: '🔶' },
{ label: '🔷blue | diamond | geometric', value: '🔷' },
{ label: '🔸diamond | geometric | orange', value: '🔸' },
{ label: '🔹blue | diamond | geometric', value: '🔹' },
{ label: '🔺geometric | red', value: '🔺' },
{ label: '🔻down | geometric| red', value: '🔻' },
{ label: '💠comic | diamond| geometric | inside', value: '💠' },
{ label: '🔘button | geometric | radio', value: '🔘' },
{ label: '🔲button | geometric | square', value: '🔲' },
{ label: '🔳button | geometric | outlined | square', value: '🔳' },
{ label: '⚪circle | geometric', value: '⚪' },
{ label: '⚫circle | geometric', value: '⚫' },
{ label: '🔴circle | geometric| red', value: '🔴' },
{ label: '🔵blue | circle | geometric', value: '🔵' },
{ label: '🏁checkered | chequered | racing', value: '🏁' },
{ label: '🚩post', value: '🚩' },
{ label: '🎌celebration | cross | crossed | Japanese', value: '🎌' }

];
